### ISSUE TITLE
Slack invite link is broken

### ISSUE THREAD

**Issue by akevdmeer** [istio/community#1039]
Slack invite link is broken.
https://istio.io/latest/get-involved/

I found this has happened before:
https://github.com/istio/community/issues/885

**Comment by kfaseela** [comment]
@SkyfireFrancisZ who can help with this?

**Comment by SkyfireFrancisZ** [comment]
I just redeployed the cloudrun instance with the new invite URL, please try it and verify.

**Comment by kfaseela** [comment]
@akevdmeer could you please check if your issue is solved now, and close this if things are working as expected?

**Comment by akevdmeer** [comment]
Works, thank you!

**Comment by kfaseela** [comment]
thanks @SkyfireFrancisZ :)

**Comment by SkyfireFrancisZ** [comment]
the pleasure is all mine
