### ISSUE TITLE
Getting error when deploying through Helm

### ISSUE THREAD

**Issue by rahul2393** [istio/community#110]
I was trying to deploy on clean cluster
My Helm version is 2.12

![screen shot 2018-12-19 at 1 26 47 pm](https://user-images.githubusercontent.com/18293335/50206920-f90d0780-0392-11e9-8b71-4739667a7b9a.png)

**Comment by rahul2393** [comment]
I used 2.10 version of Helm and was able to deploy it successfully, so there is the issue while deploying when Helm version > 2.10

**Comment by sdake** [comment]
@rahul2393 can you file your issues in the main Istio issue tracker here?

https://github.com/istio/istio/issues

Issues in this repository are for governance changes.

Cheers
-steve
