### ISSUE TITLE
Slack invite link is broken: 2023/7/11

### ISSUE THREAD

**Issue by frauniki** [istio/community#1123]
Same problem as #1039 .
https://slack.istio.io/

Istio.io slack invite link has expired.
Could you update to the new link?

**Comment by kfaseela** [comment]
@SkyfireFrancisZ

**Comment by howardjohn** [comment]
Should be fixed. Thanks

**Comment by howardjohn** [comment]
Added to terraform as well https://github.com/istio/test-infra/pull/4900
