### ISSUE TITLE
Organization Membership Request for sburton84

### ISSUE THREAD

**Issue by sburton84** [istio/community#115]
### GitHub user id
- sburton84

### Company affiliation
- Thales eSecurity

### Requirements
- [x] I have reviewed the [community membership guidelines](https://github.com/istio/community/blob/master/ROLES.md#member)
- [x] I have reviewed the [contribution guidelines](https://github.com/istio/community/blob/master/CONTRIBUTING.md)
- [x] I have enabled [2FA on my GitHub account](https://github.com/settings/security)
- [x] I have subscribed to [contributors](https://discuss.istio.io/c/contributors)
- [ ] I have made multiple contributions to the project or community.
- [x] I have two sponsors that meet the sponsorship requirements listed in the [community roles](https://github.com/istio/community/blob/master/ROLES.md#sponsor).
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to +1 on this issue to confirm they agree to sponsor this application.

### List of sponsors
- @nickrmc83
- @tnwang

### List of contributions to the Istio project
- Security Working Group involvement

### Slack access
- seanjburton@gmail.com

### **NOTE TO SPONSORS**

Please assess the list of contributions and provide a short few sentences as a comment to this issue why you approve
sponsorship, and include an `/lgtm` in the comment.

**Comment by tnwang** [comment]
Sean will be contributing mainly on work on the Istio and Envoy [OIDCFilter feature](https://docs.google.com/document/d/1mGpUsRgmA9wPB73trfTiB9YUuwYh-31iulYg9USxe0Y/edit) previously shared in the Istio Security working group , and attending the Istio Security Working Group for reviewing and contributing features. We'd like him to be added to Istio slack where our existing collaborators are communicating on the ongoing feature progress.

**Comment by nickrmc83** [comment]
/lgtm

@sburton84  will be working with me and the Pivotal team to help deliver the OpenID Connect feature @tnwang linked above as well as ongoing participation in the istio Security WG. @sburton84 's experience in the security domain will be a great asset for the WG.

**Comment by smawson** [comment]
We need a list of contributions to the project, please provide that and then ping this issue.

**Comment by duderino** [comment]
We will review the request for slack access next week 2/29/19.  Thank you for your patience

**Comment by linsun** [comment]
We have updated membership request criteria, please comment on this when you have 1 PR merged:

#143

**Comment by geeknoid** [comment]
Please reopen when you're ready.

Thanks.
