### ISSUE TITLE
Organization Membership Request for willsu

### ISSUE THREAD

**Issue by willsu** [istio/community#117]
### GitHub user id
- willsu

### Company affiliation
- Pivotal Software

### Requirements
- [X] I have reviewed the [community membership guidelines](https://github.com/istio/community/blob/master/ROLES.md#member)
- [X] I have reviewed the [contribution guidelines](https://github.com/istio/community/blob/master/CONTRIBUTING.md)
- [X] I have enabled [2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to [contributors](https://discuss.istio.io/c/contributors)
- [X] I have made multiple contributions to the project or community. Contributions may include, but are not limited to:
    - Authoring or reviewing PRs on GitHub
    - Filing or commenting on issues on GitHub
    - Contributing to working group or community discussions
- [X] I have two sponsors that meet the sponsorship requirements listed in the [community roles](https://github.com/istio/community/blob/master/ROLES.md#sponsor).
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to +1 on this issue to confirm they agree to sponsor this application.

### List of sponsors
- @peterhaochen47
- @tnwang

### List of contributions to the Istio project
- Istio Security Workgroup

### Slack access
- wsulzer@pivotal.io

### **NOTE TO SPONSORS**

Please assess the list of contributions and provide a short few sentences as a comment to this issue why you approve
sponsorship, and include an `/lgtm` in the comment.

**Comment by tnwang** [comment]
/lgtm

Will will be contributing mainly on work on the Istio configurations around the [OIDCFilter feature](https://docs.google.com/document/d/1mGpUsRgmA9wPB73trfTiB9YUuwYh-31iulYg9USxe0Y/edit) previously shared in the Istio Security working group, and attending the Istio Security Working Group for reviewing and contributing features. We'd like him to be added to Istio slack where our existing collaborators are communicating on the ongoing feature progress.

**Comment by peterhaochen47** [comment]
/lgtm

@tnwang has summarized very well the work Will Sulzer will be doing.

**Comment by smawson** [comment]
Please provide a list of concrete contributions to the Istio project, thanks!

**Comment by willsu** [comment]
Greetings @smawson. Right, so my contributions have largely been a work in progress thus far. We have made some considerable progress on adding OIDCFilter to the Authentication Istio Resource. We have a working prototype of our solution, and we plan to present a schema proposal to the Istio community during the next meeting. Since I don't have access to the Istio Slack channel, I haven't been as involved with the community as I would have liked. Today, at 11 AM PDT, I will attend the Istio Security Working Group meeting. We plan to show some initial prototyping and status updating of our progress thus far. So, other than a lot of back office type of work, it's hard for me to point to anything concrete given my current access levels. If this does not suffice, what would you suggest to better get involved in this early approval stage? Is PR review the best way for me to move forward to demonstrate concrete contributions? Thanks again.

**Comment by duderino** [comment]
We will review the request for slack access next week 2/29/19.  Thank you for your patience.

In terms of making a contribution via PR reviews:  yes, this is a great way to make a contribution

**Comment by linsun** [comment]
We have updated membership request criteria, please comment on this when you have 1 PR merged:

#143

**Comment by geeknoid** [comment]
Please reopen when you're ready.
