### ISSUE TITLE
REQUEST: New membership for Phillip 

### ISSUE THREAD

**Issue by pitlv2109** [istio/community#119]
### GitHub user id
- pitlv2109

### Company affiliation
- Google

### Requirements
- [X] I have reviewed the [community membership guidelines](https://github.com/istio/community/blob/master/ROLES.md#member)
- [X] I have reviewed the [contribution guidelines](https://github.com/istio/community/blob/master/CONTRIBUTING.md)
- [X] I have enabled [2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to [contributors](https://discuss.istio.io/c/contributors)
- [X] I have made multiple contributions to the project or community. Contributions may include, but are not limited to:
    - Authoring or reviewing PRs on GitHub
    - Filing or commenting on issues on GitHub
    - Contributing to working group or community discussions
- [X] I have two sponsors that meet the sponsorship requirements listed in the [community roles](https://github.com/istio/community/blob/master/ROLES.md#sponsor).
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to +1 on this issue to confirm they agree to sponsor this application.

### List of sponsors
- @yangminzhu   
- @jimmycyj

### List of contributions to the Istio project
- PRs merged
https://github.com/istio/istio/pull/11544
https://github.com/istio/test-infra/pull/1168
https://github.com/istio/test-infra/pull/1176
https://github.com/istio/istio/pull/11766
https://github.com/istio/istio/pull/11712

- Issues responded to
https://github.com/istio/istio/issues/11516
https://github.com/istio/istio/issues/11564
https://github.com/istio/istio/issues/11569
https://github.com/istio/istio/issues/9520

- Workgroup(s) I am involved with: Security

### Slack access
- If you'd like to join our developer Slack workspace, what is the email address you have associated with Slack?

philliple@google.com

### **NOTE TO SPONSORS**

Please assess the list of contributions and provide a short few sentences as a comment to this issue why you approve
sponsorship, and include an `/lgtm` in the comment.

**Comment by yangminzhu** [comment]
Phillip has joined the team and working on the security group full time, specifically on the auth policy. Phillip has finished the requirements and is now actively working on the AuthZ v2 implementation.
/lgtm

**Comment by smawson** [comment]
TOC has approved, Martin will add, thanks!

**Comment by pitlv2109** [comment]
Thanks guys!

**Comment by geeknoid** [comment]
Welcome!
