### ISSUE TITLE
Slack Access

### ISSUE THREAD

**Issue by rlenferink** [istio/community#121]
I'd like to start contributing to Istio and would like slack access. My e-mail address is lenferinkroy@gmail.com

Is there anything else I need to do/provide?

**Comment by louiscryan** [comment]
Please follow the template when creating a membership request

https://github.com/istio/community/issues/new?template=organization-membership-request.md

**Comment by linsun** [comment]
Sorry we don't have a direct way to open up slack access.

You'll need to open an issue in this repo by following this template to get the membership then you'll be granted slack access:  https://github.com/istio/community/blob/master/.github/ISSUE_TEMPLATE/organization-membership-request.md

**Comment by rlenferink** [comment]
Thanks for your responses @louiscryan and @linsun. Will do!
