### ISSUE TITLE
REQUEST: New membership for SataQiu

### ISSUE THREAD

**Issue by SataQiu** [istio/community#124]
### GitHub user id
- SataQiu

### Company affiliation
- Individual

### Requirements
- [x] I have reviewed the [community membership guidelines](https://github.com/istio/community/blob/master/ROLES.md#member)
- [x] I have reviewed the [contribution guidelines](https://github.com/istio/community/blob/master/CONTRIBUTING.md)
- [x] I have enabled [2FA on my GitHub account](https://github.com/settings/security)
- [x] I have subscribed to [contributors](https://discuss.istio.io/c/contributors)
- [x] I have made multiple contributions to the project or community. Contributions may include, but are not limited to:
    - Authoring or reviewing PRs on GitHub
    - Filing or commenting on issues on GitHub
    - Contributing to working group or community discussions
- [x] I have two sponsors that meet the sponsorship requirements listed in the [community roles](https://github.com/istio/community/blob/master/ROLES.md#sponsor).
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to +1 on this issue to confirm they agree to sponsor this application.

### List of sponsors
- @rootsongjc 
- @fleeto

### List of contributions to the Istio project
- PRs merged
  istio/istio.io#3263
  istio/istio.io#3247
  istio/istio.io#3225
  istio/istio.io#3066
  istio/istio.io#3054
  istio/istio.io#3047
  istio/istio.io#3042
  istio/istio.io#3041
  istio/istio.io#3040
  istio/istio.io#3039
  istio/istio.io#3037
  istio/istio.io#3036
  istio/istio.io#3031
  istio/istio.io#3030
  istio/istio.io#3029
  istio/istio.io#3028
  istio/istio.io#3025
  istio/istio.io#3023
  istio/istio.io#2971
  istio/istio.io#2954
  istio/istio.io#2913
  istio/istio#9953
  
### Slack access
- 1527062125@qq.com

I will continue to participate in the community and hope to make more contributions in the future!

**Comment by fleeto** [comment]
+1 +1, thanks @SataQiu for the contribution!

**Comment by rootsongjc** [comment]
@SataQiu +1 Thank you for your contribution and keep going on.

**Comment by smawson** [comment]
TOC says LGTUs, Martin will add.

**Comment by leecalcote** [comment]
Welcome @SataQiu!

**Comment by geeknoid** [comment]
Welcome!
