### ISSUE TITLE
Twitter logo update required

### ISSUE THREAD

**Issue by tmsagarofficial** [istio/community#1240]
I would like to point out that the Twitter logo needs to be replaced with a X. 
Pls assign this issue to me and I might need some help too on the side to learn more about this project

**Comment by kfaseela** [comment]
You can refer this file : https://github.com/istio/istio.io/blob/master/data/companies.yml

**Comment by kfaseela** [comment]
I cannot see twitter logo there though. Could you please point me to the istio.io page where the logo needs an update, so that I can point you to the right place?

**Comment by kfaseela** [comment]
Looks like it is picked from here: https://github.com/istio/istio.io/tree/master/src/icons

**Comment by kfaseela** [comment]
Fixed via https://github.com/istio/istio.io/pull/14053
