### ISSUE TITLE
Archiving old_issues_repo

### ISSUE THREAD

**Issue by rlenferink** [istio/community#125]
Is there a reason why https://github.com/istio/old_issues_repo is not archived?

It seems other repos are archived though:
https://github.com/istio/old_broker_repo
https://github.com/istio/old_auth_repo
https://github.com/istio/old_pilot_repo

I had a look and people are still creating issues over there. Archiving won't delete anything, but it will at least redirect people to the correct repositories.

What does everyone think ?

**Comment by geeknoid** [comment]
I left it unarchived so that issues could continue to be edited.

**Comment by geeknoid** [comment]
I archived it.
