### ISSUE TITLE
how to set a header while using delegate option in virtualservice

### ISSUE THREAD

**Issue by sanjaybaburaj** [istio/community#1253]
is it possible to add a request header while delegating to a virtualservice

![image](https://github.com/istio/community/assets/32713188/11cb9912-2131-4933-b278-afc2bca80378)

**Comment by hzxuzhonghu** [comment]
yeah, it is possible. But the delegate's header will take precedence

**Comment by sanjaybaburaj** [comment]
@hzxuzhonghu , could you please provide any sample on setting a request header to a delegare virtual service, I tried giving the request header, but its not showing any request header while checking the network console of browser,

**Comment by hzxuzhonghu** [comment]
can you show your delegate configuration

**Comment by sanjaybaburaj** [comment]
@hzxuzhonghu 

delegate virtual service for frontend is as follows
![image](https://github.com/istio/community/assets/32713188/61be9424-4f9d-47ba-a10e-0034c1b6c292)

**Comment by craigbox** [comment]
This repo is for discussion of the governance of the Istio project.  Please take this question to the Istio Slack or discuss.istio.io.
