### ISSUE TITLE
Add emeritus maintainers list

### ISSUE THREAD

**Issue by hzxuzhonghu** [istio/community#1262]
We have many maintainer guys that have no longer been working on istio or related work. 

https://github.com/orgs/istio/teams/maintainers

Propose removing those not working on istio. One suggestion is calculating last one year's activity/contibution from CNCF devstats.

**Comment by hzxuzhonghu** [comment]
cc @istio/steering-committee

**Comment by craigbox** [comment]
It's been about a year since https://github.com/istio/community/issues/817 so agreed on running this process again.  @therealmitchconnors, keen to drive?

**Comment by linsun** [comment]
@hzxuzhonghu i like your suggestion, which is also what i had in mind :)

>  One suggestion is calculating last one year's activity/contibution from CNCF devstats.

**Comment by howardjohn** [comment]
I was already looking into doing this, Ill send out a PR and we can go from there

**Comment by craigbox** [comment]
Can we also update https://eng.istio.io/maintainers to show the emeritus maintainers?

**Comment by linsun** [comment]
Anyone really look at eng.istio.io? I honestly haven't used it for a long time.
