### ISSUE TITLE
REQUEST: New membership for uromahn

### ISSUE THREAD

**Issue by uromahn** [istio/community#127]
### GitHub user id
- List your GitHub user id

### Company affiliation
- List your company name, or indicate Individual if you're not affiliated with a company

### Requirements
- [X] I have reviewed the [community membership guidelines](https://github.com/istio/community/blob/master/ROLES.md#member)
- [X] I have reviewed the [contribution guidelines](https://github.com/istio/community/blob/master/CONTRIBUTING.md)
- [ ] I have enabled [2FA on my GitHub account](https://github.com/settings/security)
I am accessing my GitHub account from several different machines and managing all the ssh keys in GitHub would be a nightmare. So I did not enable 2FA allowing me to push using my username and pwd.
- [X] I have subscribed to [contributors](https://discuss.istio.io/c/contributors)
- [ ] I have made multiple contributions to the project or community. Contributions may include, but are not limited to:
    - Authoring or reviewing PRs on GitHub
    - Filing or commenting on issues on GitHub
    - Contributing to working group or community discussions
- [ ] I have two sponsors that meet the sponsorship requirements listed in the [community roles](https://github.com/istio/community/blob/master/ROLES.md#sponsor).
I do not have a sponsor (yet) since we have just started looking into Istio. All I want for now is access to the Slack group to learn better from the members there. I don't want to contribute to the GitHub code base just yet. So, I am questioning the need to have a sponsor.
- [ ] I have spoken to my sponsors ahead of this application, and they have agreed to +1 on this issue to confirm they agree to sponsor this application.
See above

### List of sponsors
- I hope to find one sponsor once I could join the Slack group
- see above

### List of contributions to the Istio project
- PRs reviewed
- PRs merged
- Issues responded to
- Workgroup(s) I am involved with

### Slack access
- If you'd like to join our developer Slack workspace, what is the email address you have associated with Slack?
uromahn@box.com

### **NOTE TO SPONSORS**

Please assess the list of contributions and provide a short few sentences as a comment to this issue why you approve
sponsorship, and include an `/lgtm` in the comment.

**Comment by duderino** [comment]
Next week 2/29/19 we will review this request

**Comment by duderino** [comment]
thank you for your patience

**Comment by linsun** [comment]
We have updated membership request criteria, please comment on this when you have 1 PR merged:

https://github.com/istio/community/pull/143

**Comment by geeknoid** [comment]
Please reopen when you're ready.
