### ISSUE TITLE
Nominate Daniel Hawton as BTR maintainers

### ISSUE THREAD

**Issue by linsun** [istio/community#1302]
Hi Folks, I wanted to nominate @dhawton on BTR maintainers, I have consulted @ericvn offline and he thinks it is reasonable to open a Github issue for discussion. Daniel has been release managers for 2 releases, with one being the primary release mgr. Daniel is also maintaining the prow infrastructure at Solo for Istio so he is our internal expert at Solo on Istio's pipeline. I'll let @ericvn to chime in with his input.

**Comment by linsun** [comment]
ping @ericvn and @istio/wg-test-and-release-maintainers

**Comment by ericvn** [comment]
I would sponsor Daniel for this.

**Comment by linsun** [comment]
https://github.com/istio/community/issues/1302
