### ISSUE TITLE
Nominate Ben Leggett for istio-cni maintainer

### ISSUE THREAD

**Issue by linsun** [istio/community#1314]
Istio-cni is an important component for sidecar and even a critical component for ambient. I propose to add a few maintainers for the istio-cni node agent and I want to nominate @bleggett due to his outstanding contribution: https://github.com/istio/istio/pull/48253 along with many other contributions and reviews in this component.  Opening this issue to discuss this openly. @bleggett, feel free to add your contributions for recording purpose.

**Comment by linsun** [comment]
cc @istio/wg-networking-maintainers for comment

**Comment by howardjohn** [comment]
FWIW I don't think we formally have an "istio-cni maintainer". It is owned by the networking group more broadly. That being said I think Ben probably meets the bar (https://github.com/istio/community/blob/master/ROLES.md#requirements-3) more broadly, or is at least extremely close to doing so ( didn't look very closely here)

**Comment by linsun** [comment]
Thanks John for your input. Agree we don't have istio-cni maintainer formerly. Depends on folks' input and comfortable level, we can decide to create a dedicated group for istio-cni or have Ben join the networking maintainer group.

tagging a few networking leads for input @ramaraochavali @stevenctl @lizan

**Comment by nrjpoddar** [comment]
I think adding a CNI maintainer is a good thing to have specially w/Ambient beta on the horizon. I'm in favor of it and adding @bleggett given other TOC members are good with it.

**Comment by linsun** [comment]
Thanks Neeraj. Just checked, Ben has 32 merged PR which includes substantial PR as well.  I'll let the other networking leads weigh in, if they are okay with adding Ben to networking maintainer group, we can add him there instead of forming the istio-cni maintainer.

**Comment by hzxuzhonghu** [comment]
istio-cni is a little different, with more undelying networking expertise requirements. I think a sub-group is necessary.

**Comment by zirain** [comment]
> istio-cni is a little different, with more undelying networking expertise requirements. I think a sub-group is necessary.

like networking/pilot would be better.

**Comment by ramaraochavali** [comment]
Looking at PRs, most of them are in cni area. So it makes sense to create istio-cni and add him

**Comment by linsun** [comment]
@ramaraochavali @hzxuzhonghu @zirain thank you for the feedback! Seems you all are good with moving forward to promote Ben as istio-cni maintainer.

@stevenctl @lizan any feedback from you, please let me know by end of today.

**Comment by zirain** [comment]
To be clear, it's good to create an sub-group named istio/wg-networking-maintainers-cni, and grant authority with `/cni` folder.

**Comment by linsun** [comment]
I'd like to do a vote from networking maintainers and leads.  Leads' vote count, maintainers vote are helpful:

option 1: create dedicated group for istio-cni and promote Ben to istio-cni maintainer
option 2: promote Ben to wg-networking-maintainers.

Please use emojis (option 1 heart, option 2: rocket)

**Comment by linsun** [comment]
cc @istio/wg-networking-maintainers @howardjohn @stevenctl @lizan @ramaraochavali ^^^^

**Comment by stevenctl** [comment]
+1 to John's comment.
Also big +1 to making @bleggett a maintainer

**Comment by linsun** [comment]
@stevenctl thanks, can you vote on here with your desired emoji?  https://github.com/istio/community/issues/1314#issuecomment-1917002184

**Comment by linsun** [comment]
Added this to the agenda of tmr's WG meeting, please vote here - https://github.com/istio/community/issues/1314#issuecomment-1917002184

**Comment by srampal** [comment]
+1 for @bleggett  as maintainer!

**Comment by linsun** [comment]
Notes from today's WG meeting: @bleggett is approved as networking WG maintainers, there is no objection recorded in the meeting. I'll submit a PR shortly.
