### ISSUE TITLE
Nominate Iris Ding for istio-cni maintainer

### ISSUE THREAD

**Issue by linsun** [istio/community#1315]
Similar as https://github.com/istio/community/issues/1314, I want to nominate @irisdingbj for her outstanding contribution to this component. Opening this issue to discuss this openly.  @irisdingbj feel free to add your contributions for recording purpose.

**Comment by linsun** [comment]
cc @istio/wg-networking-maintainers for comment

**Comment by nrjpoddar** [comment]
Approved from my end

**Comment by linsun** [comment]
tagging leads to comment @stevenctl @ramaraochavali @lizan @howardjohn

**Comment by ramaraochavali** [comment]
I am fine adding @irisdingbj as cni maintainer

**Comment by linsun** [comment]
Notes from today's WG meeting: @irisdingbj  we appreciate your interest in serving as istio-cni maintainer and we recognized your substantial contribution to Istio, which is also reflected that you are currently maintainers in multiple groups of Istio. We would love to see more contributions from you on the networking area PRs and reviewing other's networking area PRs before we can approve this. Hope to see you shine more in the community!
