### ISSUE TITLE
Nominate PlatformLC for istio-cni maintainer

### ISSUE THREAD

**Issue by linsun** [istio/community#1316]
Similar as https://github.com/istio/community/issues/1314, I want to nominate @PlatformLC for his contribution to this component. Opening this issue to discuss this openly.  @PlatformLC  feel free to add your contributions for recording purpose.

**Comment by linsun** [comment]
cc @istio/wg-networking-maintainers for comment

**Comment by howardjohn** [comment]
We have a standard process for maintainership: https://github.com/istio/community/blob/master/ROLES.md#requirements-3 which I don't think is currently met here. However, its great to see the interest here! If you are interested in progressing more as a maintainer feel free to reach out to me or others to help guide you along on how best to get from here to there

**Comment by linsun** [comment]
Thanks John for your comments. That is fair, opening this for transparency and recording purpose.

**Comment by linsun** [comment]
tagging @istio/wg-networking-maintainers and leads to comment @stevenctl @ramaraochavali @lizan

**Comment by linsun** [comment]
I did a quick calculation yesterday myself, I think @PlatformLC has around 15 merged PRs. This confirms John's comment earlier. Leaving this open for others to comment on it.

**Comment by ramaraochavali** [comment]
+1 to wait for a bit more

**Comment by irisdingbj** [comment]
If we have consensus for having a sub istio-cni group, I will vote for @PlatformLC to be part of the maintainer of this subgroup.  As @PlatformLC has strong experience in this component and the big ebpf redireciton PR is a big plus for this.  Besides his other contributions to ztunnel is also related with area.

**Comment by linsun** [comment]
Added this to the agenda of tmr's WG meeting.

**Comment by linsun** [comment]
Notes from today's WG meeting: @PlatformLC we appreciate your interest in serving as istio-cni maintainer, we would love to see more contributions from you on PRs and reviewing other's PRs before we can approve this. Hope to see you shine more in the community!
