### ISSUE TITLE
Considering adding github discussions contribution to istio steering contribution seat calculation

### ISSUE THREAD

**Issue by linsun** [istio/community#1320]
as titled, github discussion contributions should be encouraged among contributors similar as general github contributions.

**Comment by craigbox** [comment]
We remain limited by the events that are emitted from the GitHub API, which unfortunately do not include any relating to discussions.

We would have to do some sort of search or export of the discussions to be able to include them, and as with everything, apply some discretion: a thread answered immediately and authoritatively is "worth more" than a thread with 20 different back-and-forth messages and no resolution.

I'm going to close this as "not feasible" at this point, and we can include this thinking in the steering formula calculation we are now obliged to do.
