### ISSUE TITLE
REQUEST: New membership for ericvn

### ISSUE THREAD

**Issue by ericvn** [istio/community#133]
### GitHub user id
- ericvn

### Company affiliation
- IBM

### Requirements
- [x] I have reviewed the [community membership guidelines](https://github.com/istio/community/blob/master/ROLES.md#member)
- [x] I have reviewed the [contribution guidelines](https://github.com/istio/community/blob/master/CONTRIBUTING.md)
- [x] I have enabled [2FA on my GitHub account](https://github.com/settings/security)
- [x] I have subscribed to [contributors](https://discuss.istio.io/c/contributors)
- [x] I have made multiple contributions to the project or community. Contributions may include, but are not limited to:
    - Authoring or reviewing PRs on GitHub
    - Filing or commenting on issues on GitHub
    - Contributing to working group or community discussions
- [x] I have two sponsors that meet the sponsorship requirements listed in the [community roles](https://github.com/istio/community/blob/master/ROLES.md#sponsor).
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to +1 on this issue to confirm they agree to sponsor this application.

### List of sponsors
- @linsun 
- @sdake 

### List of contributions to the Istio project
- PRs reviewed
https://github.com/istio/istio.io/pull/3335
https://github.com/istio/istio/pull/11956
- PRs merged
https://github.com/istio/istio/pull/11942
https://github.com/istio/istio/pull/11421
https://github.com/istio/istio.io/pull/3333
https://github.com/istio/istio.io/pull/3327 (to be merged soon)
https://github.com/istio/istio.io/pull/3320
https://github.com/istio/istio.io/pull/3171
https://github.com/istio/istio.io/pull/3141
https://github.com/istio/istio.io/pull/3184
https://github.com/istio/istio.io/pull/3183
https://github.com/istio/istio.io/pull/3171
https://github.com/istio/istio.io/pull/3141
- Issues responded to
https://github.com/istio/istio/issues/11125
https://github.com/istio/istio.io/issues/3321
- Workgroup(s) I am involved with
Still trying to find the best fit, but attending several WG Meetings including, networking, testing, and performance.
### Slack access
- ericvn@us.ibm.com

### **NOTE TO SPONSORS**

Please assess the list of contributions and provide a short few sentences as a comment to this issue why you approve
sponsorship, and include an `/lgtm` in the comment.

[update: change sponsor to @sdake as mentioned on TOC call)

**Comment by linsun** [comment]
+1 @ericvn you have my support

**Comment by duderino** [comment]
Conditional approval.  TOC will ratify next week

**Comment by sdake** [comment]
+1 @sdake will sponsor.

**Comment by linsun** [comment]
I believe Eric is auto approved with the new process.  I have granted him the GitHub permission.
