### ISSUE TITLE
REQUEST: New membership for @ibm-jason

### ISSUE THREAD

**Issue by ibm-jason** [istio/community#135]
### GitHub user id

@ibm-jason

### Company affiliation

IBM

### Requirements
- [X] I have reviewed the [community membership guidelines](https://github.com/istio/community/blob/master/ROLES.md#member)
- [X] I have reviewed the [contribution guidelines](https://github.com/istio/community/blob/master/CONTRIBUTING.md)
- [X] I have enabled [2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to [contributors](https://discuss.istio.io/c/contributors)
- [X] I have made multiple contributions to the project or community. Contributions may include, but are not limited to:
    - Authoring or reviewing PRs on GitHub
    - Filing or commenting on issues on GitHub
    - Contributing to working group or community discussions
- [X] I have two sponsors that meet the sponsorship requirements listed in the [community roles](https://github.com/istio/community/blob/master/ROLES.md#sponsor).
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to +1 on this issue to confirm they agree to sponsor this application.

### List of sponsors
- @linsun 
- TBD

### List of contributions to the Istio project
- PRs reviewed: n/a
- PRs merged:
  - https://github.com/istio/istio.io/pull/3209
  - https://github.com/istio/istio.io/pull/3197
- Issues responded to:
  - https://github.com/istio/istio.io/issues/3312
  - https://github.com/istio/istio/issues/11527
  - https://github.com/istio/istio/issues/11044
  - https://github.com/istio/istio/issues/10134
  - https://github.com/istio/istio/issues/5043
- Workgroup(s) I am involved with:
  - Istio UX Working Group

### Slack access
- If you'd like to join our developer Slack workspace, what is the email address you have associated with Slack?

jason.clark.oss@gmail.com

### **NOTE TO SPONSORS**

Please assess the list of contributions and provide a short few sentences as a comment to this issue why you approve
sponsorship, and include an `/lgtm` in the comment.

**Comment by linsun** [comment]
/lgtm

I'll invite Jason to the GitHub org and slack.
