### ISSUE TITLE
REQUEST: New membership for @therealmitchconnors

### ISSUE THREAD

**Issue by therealmitchconnors** [istio/community#136]
### GitHub user id
- List your GitHub user id

### Company affiliation
- List your company name, or indicate Individual if you're not affiliated with a company

### Requirements
- [x] I have reviewed the [community membership guidelines](https://github.com/istio/community/blob/master/ROLES.md#member)
- [x] I have reviewed the [contribution guidelines](https://github.com/istio/community/blob/master/CONTRIBUTING.md)
- [x] I have enabled [2FA on my GitHub account](https://github.com/settings/security)
- [x] I have subscribed to [contributors](https://discuss.istio.io/c/contributors)
- [x] I have made multiple contributions to the project or community. Contributions may include, but are not limited to:
    - Authoring or reviewing PRs on GitHub
    - Filing or commenting on issues on GitHub
    - Contributing to working group or community discussions
- [x] I have two sponsors that meet the sponsorship requirements listed in the [community roles](https://github.com/istio/community/blob/master/ROLES.md#sponsor).
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to +1 on this issue to confirm they agree to sponsor this application.

### List of sponsors
- @mandarjog
- @geeknoid 

### List of contributions to the Istio project
- PRs reviewed: https://github.com/istio/tools/pull/67
- PRs merged: https://github.com/istio/tools/pull/64, 
- Issues responded to: https://github.com/istio/istio/issues/11488, https://github.com/istio/istio/issues/11919
- Workgroup(s) I am involved with: config, user experience

### Slack access
- If you'd like to join our developer Slack workspace, what is the email address you have associated with Slack?

### **NOTE TO SPONSORS**

Please assess the list of contributions and provide a short few sentences as a comment to this issue why you approve
sponsorship, and include an `/lgtm` in the comment.

**Comment by mandarjog** [comment]
Mitch has been running / debugging and updating release qualification cluster for about 2 months now.  He has been chasing difficult scalability issues that are not captured in PRs yet.
I support his membership.
/lgtm

**Comment by geeknoid** [comment]
Welcome aboard!
