### ISSUE TITLE
REQUEST: New membership for rcernich

### ISSUE THREAD

**Issue by knrc** [istio/community#138]
Based on new membership requirements

### GitHub user id
- rcernich

### Company affiliation
- Red Hat

### Requirements
- [x] I have reviewed the [community membership guidelines](https://github.com/istio/community/blob/master/ROLES.md#member)
- [x] I have reviewed the [contribution guidelines](https://github.com/istio/community/blob/master/CONTRIBUTING.md)
- [x] I have enabled [2FA on my GitHub account](https://github.com/settings/security)
- [x] I have subscribed to [contributors](https://discuss.istio.io/c/contributors)
- [x] I have made multiple contributions to the project or community. Contributions may include, but are not limited to:
    - Authoring or reviewing PRs on GitHub
    - Filing or commenting on issues on GitHub
    - Contributing to working group or community discussions
- [x] I have two sponsors that meet the sponsorship requirements listed in the [community roles](https://github.com/istio/community/blob/master/ROLES.md#sponsor).
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to +1 on this issue to confirm they agree to sponsor this application.

### List of contributions to the Istio project
- PRs reviewed
- PRs merged
https://github.com/istio/tools/pull/37
https://github.com/istio/tools/pull/49

- PRs open
https://github.com/istio/api/pull/764

- Issues responded to
- Workgroup(s) I am involved with

### Slack access
- If you'd like to join our developer Slack workspace, what is the email address you have associated with Slack?

### **NOTE TO SPONSORS**

Please assess the list of contributions and provide a short few sentences as a comment to this issue why you approve
sponsorship, and include an `/lgtm` in the comment.

**Comment by linsun** [comment]
just invited you to GitHub org.
