### ISSUE TITLE
REQUEST: New membership for brian-avery

### ISSUE THREAD

**Issue by knrc** [istio/community#140]
Based on new membership requirements

### GitHub user id
- @brian-avery

### Company affiliation
- Red Hat

### Requirements
- [x] I have reviewed the [community membership guidelines](https://github.com/istio/community/blob/master/ROLES.md#member)
- [x] I have reviewed the [contribution guidelines](https://github.com/istio/community/blob/master/CONTRIBUTING.md)
- [x] I have enabled [2FA on my GitHub account](https://github.com/settings/security)
- [x] I have subscribed to [contributors](https://discuss.istio.io/c/contributors)
- [x] I have made multiple contributions to the project or community. Contributions may include, but are not limited to:
    - Authoring or reviewing PRs on GitHub
    - Filing or commenting on issues on GitHub
    - Contributing to working group or community discussions
- [x] I have two sponsors that meet the sponsorship requirements listed in the [community roles](https://github.com/istio/community/blob/master/ROLES.md#sponsor).
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to +1 on this issue to confirm they agree to sponsor this application.

### List of contributions to the Istio project
- Issues opened
https://github.com/istio/istio.io/issues/3398
https://github.com/istio/istio.io/issues/3322
https://github.com/istio/istio.io/issues/3311
https://github.com/istio/istio.io/issues/3284
https://github.com/istio/istio.io/pull/3399
https://github.com/istio/istio.io/issues/137
https://github.com/istio/istio/issues/9432
https://github.com/istio/istio/issues/9277
https://github.com/istio/istio/issues/8887
https://github.com/istio/istio/issues/6298
https://github.com/istio/istio.io/issues/3302
https://github.com/istio/istio/issues/6206
https://github.com/istio/istio/pull/6207

- PRs reviewed
- PRs merged
https://github.com/istio/istio.io/pull/3380
https://github.com/istio/istio.io/pull/3351
https://github.com/istio/istio.io/pull/3324
https://github.com/istio/istio.io/pull/3293
https://github.com/istio/istio.io/pull/3273
https://github.com/istio/istio.io/pull/2853
https://github.com/istio/istio.io/pull/1986
https://github.com/istio/istio.io/pull/1808
https://github.com/istio/istio.io/pull/3273

- PRs open

Incremental xDS - https://github.com/istio/istio/issues/6299

- Issues responded to
- Workgroup(s) I am involved with
Usability, Environment, Config, Policies

### Slack access
- If you'd like to join our developer Slack workspace, what is the email address you have associated with Slack?

### **NOTE TO SPONSORS**

Please assess the list of contributions and provide a short few sentences as a comment to this issue why you approve
sponsorship, and include an `/lgtm` in the comment.

**Comment by linsun** [comment]
just invited to GitHub org - welcome

/lgtm

**Comment by brian-avery** [comment]
Thanks @linsun!
