### ISSUE TITLE
REQUEST: New membership for leecalcote

### ISSUE THREAD

**Issue by leecalcote** [istio/community#142]
I’m just now identifying that I was fast-tracked through Istio membership and invited to Slack some long time ago, but my github handle wasn’t identified as a member.

### GitHub user id
[leecalcote](https://github.com/leecalcote)

### Company affiliation
Layer5

### Requirements
- [x] I have reviewed the [community membership guidelines](https://github.com/istio/community/blob/master/ROLES.md#member)
- [x] I have reviewed the [contribution guidelines](https://github.com/istio/community/blob/master/CONTRIBUTING.md)
- [x] I have enabled [2FA on my GitHub account](https://github.com/settings/security)
- [x] I have subscribed to [contributors](https://discuss.istio.io/c/contributors)
- [x] I have made multiple contributions to the project or community. Contributions may include, but are not limited to:
    - Authoring or reviewing PRs on GitHub
    - Filing or commenting on issues on GitHub
    - Contributing to working group or community discussions
- [x] I have two sponsors that meet the sponsorship requirements listed in the [community roles](https://github.com/istio/community/blob/master/ROLES.md#sponsor).
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to +1 on this issue to confirm they agree to sponsor this application.

### List of sponsors
- @venilnoronha 
- @geeknoid

### List of contributions to the Istio project
- PRs merged
  - In `istio.io` repo - https://github.com/istio/istio.io/commits?author=leecalcote
  - In `community` repo - https://github.com/istio/community/commits?author=leecalcote
  - In `istio` repo - 
  - https://github.com/istio/istio.io/pull/1617
  - https://github.com/istio/istio/pull/2463/commits/7bb82bed82190625cbe41df0a32a8fc9bb1c038a
- Workgroup(s) I am involved with:
  - Telemetry & Policies (my team created a Mixer adapter early on)
  - UX (as a possible co-lead)
  - Attend TOC meeting with regularity
  - Docs (as a possible co-lead)

### Slack access
- I already have Slack access.

### **NOTE TO SPONSORS**

Please assess the list of contributions and provide a short few sentences as a comment to this issue why you approve
sponsorship, and include an `/lgtm` in the comment.

**Comment by venilnoronha** [comment]
@leecalcote has been improving Istio docs, and his nomination to be a member is consistent with #143.

/lgtm

**Comment by linsun** [comment]
invited you to GitHub, welcome

**Comment by leecalcote** [comment]
Thank you, @linsun!
