### ISSUE TITLE
REQUEST: Resend GitHub invitation for krapie (changed/reverted username; missed 7 day acceptance deadline)

### ISSUE THREAD

**Issue by krapie** [istio/community#1433]
I've changed my username krapie to @kevinprk, and got removed from Istio organization. I'm requesting to re-invite me into the organization.

I joined Istio organization by this PR: https://github.com/istio/community/pull/1027

**Comment by hzxuzhonghu** [comment]
File an pr to update your id

**Comment by krapie** [comment]
@hzxuzhonghu I'm reverting my username to @krapie :)

**Comment by hzxuzhonghu** [comment]
what do you mean, i can see you are in https://github.com/istio/community/blob/master/org/members.yaml#L248

**Comment by hzxuzhonghu** [comment]
Need to resend the invitation? @linsun @kfaseela

**Comment by krapie** [comment]
@hzxuzhonghu Oh I'm just not changing my username and keeping using the old username, so I don't need to change the file. I think I just need to get invitation from the Istio Automation.

**Comment by kfaseela** [comment]
Let me check how to do this, worst case the user can remove and re-add themselves .

**Comment by kfaseela** [comment]
But what happened to the previous invite you received when you added yourselves? You told you are retaining your id and not changing? The title is a bit confusing

**Comment by krapie** [comment]
@kfaseela Well the title is now outdated since I returned to my old username.

> But what happened to the previous invite you received when you added yourselves?

@istio-testing sent me invitation with 7-day expiration when I added myself with this PR: https://github.com/istio/community/pull/1027

**Comment by kfaseela** [comment]
> @kfaseela Well the title is now outdated since I returned to my old username.
> 
> > But what happened to the previous invite you received when you added yourselves?
> 
> @istio-testing sent me invitation with 7-day expiration when I added myself with this PR: https://github.com/istio/community/pull/1027

Ok, but this issue has been raised with the other username itself?

**Comment by krapie** [comment]
@kfaseela Yes, when I changed my username to other username, I got removed from Istio organization. And I requested to renew my username in the file so that I can got re-invited, just like this issue: https://github.com/istio/community/issues/725

**Comment by kfaseela** [comment]
> @kfaseela Yes, when I changed my username to other username, I got removed from Istio organization. And I requested to renew my username in the file so that I can got re-invited, just like this issue: https://github.com/istio/community/issues/725

@craigbox will you be able to resend the invite?

**Comment by craigbox** [comment]
No, I don't have any insight into the automation sorry.

**Comment by kfaseela** [comment]
> No, I don't have any insight into the automation sorry.

Eric has done for me in the past, let me check if I can find that out

**Comment by krapie** [comment]
Thanks! I have received the invitation from @istio-testing

**Comment by zirain** [comment]
there's a failed [postjob](https://prow.istio.io/view/gs/istio-prow/logs/sync-org_community_postsubmit/1810794914951204864) when you changed your id.

Once you change you github name/id, you should send a request like [this](https://github.com/istio/community/pull/1438).

**Comment by krapie** [comment]
@zirain Thanks! I will close this issue.
