### ISSUE TITLE
REQUEST: New membership for johnma14

### ISSUE THREAD

**Issue by johnma14** [istio/community#144]
If you'd like to become a member of the Istio organization on GitHub, please fill out this form and submit it.
Give us a few days to review and you should receive an invitation to join.

### GitHub user id
- johnma14

### Company affiliation
- IBM

### Requirements
- [x ] I have reviewed the [community membership guidelines](https://github.com/istio/community/blob/master/ROLES.md#member)
- [x] I have reviewed the [contribution guidelines](https://github.com/istio/community/blob/master/CONTRIBUTING.md)
- [x ] I have enabled [2FA on my GitHub account](https://github.com/settings/security)
- [ x] I have subscribed to [contributors](https://discuss.istio.io/c/contributors)

Provide a link to at least one PR that you have successfully pushed to one
of the Istio repos

https://github.com/istio/istio.io/pull/3188

**Comment by linsun** [comment]
welcome, just sent an invite to join GitHub and slack.
