### ISSUE TITLE
REQUEST: New membership for rvennam

### ISSUE THREAD

**Issue by rvennam** [istio/community#147]
### GitHub user id
- rvennam

### Company affiliation
- IBM

### Requirements
- [x] I have reviewed the [community membership guidelines](https://github.com/istio/community/blob/master/ROLES.md#member)
- [x] I have reviewed the [contribution guidelines](https://github.com/istio/community/blob/master/CONTRIBUTING.md)
- [x] I have enabled [2FA on my GitHub account](https://github.com/settings/security)
- [x] I have subscribed to [contributors](https://discuss.istio.io/c/contributors)

Provide a link to at least one PR that you have successfully pushed to one
of the Istio repos
- https://github.com/istio/istio/pull/10649
- https://github.com/istio/istio/pull/10559
- https://github.com/istio/istio.io/pull/3011

**Comment by linsun** [comment]
welcome, you should be all set!
