### ISSUE TITLE
Working group calendar links broken

### ISSUE THREAD

**Issue by jaellio** [istio/community#1472]
The links for the working group calendar and the link to add the working group calendar to a google account are broken. 

https://github.com/istio/community/blob/master/WORKING-GROUPS.md#working-group-meetings

**Comment by keithmattix** [comment]
Hmm I think both links work for me

**Comment by kfaseela** [comment]
@jaellio what error are you getting? it works for me

**Comment by craigbox** [comment]
I've tested them too, so hopefully it was just a transient error.  Jackie, if you get further errors, please re-open.
