### ISSUE TITLE
REQUEST: New membership for listx

### ISSUE THREAD

**Issue by listx** [istio/community#149]
### GitHub user id
- listx

### Company affiliation
- Google

### Requirements
- [X] I have reviewed the [community membership guidelines](https://github.com/istio/community/blob/master/ROLES.md#member)
- [x] I have reviewed the [contribution guidelines](https://github.com/istio/community/blob/master/CONTRIBUTING.md)
- [X] I have enabled [2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to [contributors](https://discuss.istio.io/c/contributors)

Provide a link to at least one PR that you have successfully pushed to one
of the Istio repos

https://github.com/istio/istio/pull/7712

**Comment by geeknoid** [comment]
Invitation sent. Welcome!
