### ISSUE TITLE
REQUEST: New membership for zhaohuabing

### ISSUE THREAD

**Issue by zhaohuabing** [istio/community#150]
If you'd like to become a member of the Istio organization on GitHub, please fill out this form and submit it.
Give us a few days to review and you should receive an invitation to join.

### GitHub user id
zhaohuabing

### Company affiliation
- ZTE

### Requirements
- [x] I have reviewed the [community membership guidelines](https://github.com/istio/community/blob/master/ROLES.md#member)
- [x] I have reviewed the [contribution guidelines](https://github.com/istio/community/blob/master/CONTRIBUTING.md)
- [x] I have enabled [2FA on my GitHub account](https://github.com/settings/security)
- [x] I have subscribed to [contributors](https://discuss.istio.io/c/contributors)

Provide a link to at least one PR that you have successfully pushed to one
of the Istio repos
- Support multiple network interfaces (https://github.com/istio/istio/pull/9688)
- Use ServiceMeta to convey the protocol and other service properties (https://github.com/istio/istio/pull/9713)
- Avoid unnecessary service change events (https://github.com/istio/istio/pull/12148)
- Translate V1alpha3 routing introduction blog to Chinese (https://github.com/istio/istio.io/pull/1615)
- Translate traffic-shifting task to Chinese (https://github.com/istio/istio.io/pull/1632)
- Translate request-routing into Chinese (https://github.com/istio/istio.io/pull/1654)

**Comment by geeknoid** [comment]
Invitation sent. Welcome!

**Comment by zhaohuabing** [comment]
@geeknoid Is it possible to change my company affiliation? I have moved to another company.

Thanks
