### ISSUE TITLE
REQUEST: New membership for holgero

### ISSUE THREAD

**Issue by holgero** [istio/community#152]
If you'd like to become a member of the Istio organization on GitHub, please fill out this form and submit it.
Give us a few days to review and you should receive an invitation to join.

### GitHub user id
- holgero

### Company affiliation
- SAP SE

### Requirements
- [x] I have reviewed the [community membership guidelines](https://github.com/istio/community/blob/master/ROLES.md#member)
- [x] I have reviewed the [contribution guidelines](https://github.com/istio/community/blob/master/CONTRIBUTING.md)
- [x] I have enabled [2FA on my GitHub account](https://github.com/settings/security)
- [x] I have subscribed to [contributors](https://discuss.istio.io/c/contributors)

Provide a link to at least one PR that you have successfully pushed to one
of the Istio repos
* on istio.io:
  * https://github.com/istio/istio.io/pull/1961
  * https://github.com/istio/istio.io/pull/1506
* on istio:
  * https://github.com/istio/istio/pull/10831
  * https://github.com/istio/istio/pull/5779
  * https://github.com/istio/istio/pull/5665
  * https://github.com/istio/istio/pull/5556
  * https://github.com/istio/istio/pull/5505
  * https://github.com/istio/istio/pull/5501
  * https://github.com/istio/istio/pull/5496
  * https://github.com/istio/istio/pull/5495
  * https://github.com/istio/istio/pull/5494

**Comment by geeknoid** [comment]
Invitation sent. Welcome!

**Comment by holgero** [comment]
Invitation accepted. Thank you!
