### ISSUE TITLE
REQUEST: New membership for rlenferink

### ISSUE THREAD

**Issue by rlenferink** [istio/community#153]
### GitHub user id
- @rlenferink 

### Company affiliation
- Working as a Software Engineer at [Thales](https://www.thalesgroup.com/en/defence) but submitting this request for myself as an individual

### Requirements
- [x] I have reviewed the [community membership guidelines](https://github.com/istio/community/blob/master/ROLES.md#member)
- [x] I have reviewed the [contribution guidelines](https://github.com/istio/community/blob/master/CONTRIBUTING.md)
- [x] I have enabled [2FA on my GitHub account](https://github.com/settings/security)
- [x] I have subscribed to [contributors](https://discuss.istio.io/c/contributors)

### Contributions
Provide a link to at least one PR that you have successfully pushed to one
of the Istio repos: https://github.com/istio/community/commits?author=rlenferink

I'd like to help out with community related tasks, but to get started with that, it would be nice to have Slack access. Therefore I'm submitting this membership request (https://github.com/istio/community/issues/121) .

**Comment by geeknoid** [comment]
You can now join Slack without being a member of the org. Just fill out this form: https://docs.google.com/forms/d/e/1FAIpQLSfdsupDfOWBtNVvVvXED6ULxtR4UIsYGCH_cQcRr0VcG1ZqQQ/viewform

Let me know if you'd like to proceed to becoming an org member, or if Slack access is sufficient.

**Comment by rlenferink** [comment]
Thanks for the quick reply @geeknoid I've submitted the form for Slack access.

If possible, I'd like to proceed with becoming an org member as well ;)

**Comment by geeknoid** [comment]
Invitation sent. Welcome!
