### ISSUE TITLE
REQUEST: New membership for xieydd

### ISSUE THREAD

**Issue by xieydd** [istio/community#154]
If you'd like to become a member of the Istio organization on GitHub, please fill out this form and submit it.
Give us a few days to review and you should receive an invitation to join.

### GitHub user id
- xieydd

### Company affiliation
- [Unisound](http://www.unisound.com/)

### Requirements
- [x] I have reviewed the [community membership guidelines](https://github.com/istio/community/blob/master/ROLES.md#member)
- [x] I have reviewed the [contribution guidelines](https://github.com/istio/community/blob/master/CONTRIBUTING.md)
- [x] I have enabled [2FA on my GitHub account](https://github.com/settings/security)
- [x] I have subscribed to [contributors](https://discuss.istio.io/c/contributors)

Provide a link to at least one PR that you have successfully pushed to one
of the Istio repos

[https://github.com/istio/istio.io/pulls/xieydd](https://github.com/istio/istio.io/pulls/xieydd)

**Comment by geeknoid** [comment]
Invitation sent. Welcome!
