### ISSUE TITLE
REQUEST: New membership for loewenstein

### ISSUE THREAD

**Issue by loewenstein** [istio/community#156]
If you'd like to become a member of the Istio organization on GitHub, please fill out this form and submit it.
Give us a few days to review and you should receive an invitation to join.

### GitHub user id
loewenstein

### Company affiliation
SAP SE

### Requirements
- [x] I have reviewed the [community membership guidelines](https://github.com/istio/community/blob/master/ROLES.md#member)
- [x] I have reviewed the [contribution guidelines](https://github.com/istio/community/blob/master/CONTRIBUTING.md)
- [x] I have enabled [2FA on my GitHub account](https://github.com/settings/security)
- [x] I have subscribed to [contributors](https://discuss.istio.io/c/contributors)

Provide a link to at least one PR that you have successfully pushed to one
of the Istio repos
- https://github.com/istio/istio/pull/11812
- https://github.com/istio/istio/pull/5207
- https://github.com/istio/istio/pull/4580
- https://github.com/istio/istio/pull/4251

PRs with multiple authors:
- https://github.com/istio/istio/pull/5496/commits
- https://github.com/istio/istio/pull/5505/commits
- https://github.com/istio/istio/pull/5556/commits
- https://github.com/istio/istio/pull/5665/commits
- https://github.com/istio/istio/pull/5779/commits

Other than that I am active in the Environments and Networking Working groups. I have been active in several github issues and coordinated contributions from our team. E.g. getting [Allow configurable trust domain in Istio identities](https://github.com/istio/istio/issues/8661) from identification to the merge of PRs took quite some communication via issue, PR comment and Slack.

**Comment by geeknoid** [comment]
Invitation sent. Welcome!

**Comment by loewenstein** [comment]
@geeknoid accepted. Thanks.
