### ISSUE TITLE
REQUEST: New membership for idouba

### ISSUE THREAD

**Issue by idouba** [istio/community#159]
If you'd like to become a member of the Istio organization on GitHub, please fill out this form and submit it.
 Give us a few days to review and you should receive an invitation to join.
 
 ### GitHub user id
 * idouba 
 ### Company affiliation
 * Huawei Technologies Co., Ltd. China

### Requirements
- [x] I have reviewed the [community membership guidelines](https://github.com/istio/community/blob/master/ROLES.md#member)
- [x] I have reviewed the [contribution guidelines](https://github.com/istio/community/blob/master/CONTRIBUTING.md)
- [x] I have enabled [2FA on my GitHub account](https://github.com/settings/security)
- [x] I have subscribed to [contributors](https://discuss.istio.io/c/contributors)

Provide a link to at least one PR that you have successfully pushed to one
of the Istio repos

* https://github.com/istio/istio/issues/12590
* https://github.com/istio/istio/issues/6070
* https://github.com/istio/istio/issues/9375
* https://github.com/istio/api/issues/837
* https://github.com/istio/istio/pull/7642
* https://github.com/istio/api/pull/539
* https://github.com/istio/istio.io/pull/3162
* https://github.com/istio/istio.io/pull/3161
* https://github.com/istio/istio.io/pull/3159
* https://github.com/istio/istio.io/pull/3157
* https://github.com/istio/istio.io/pull/3103
* https://github.com/istio/istio.io/pull/3102
* https://github.com/istio/istio/pull/9442
* https://github.com/istio/api/pull/839
* https://github.com/istio/api/pull/869
* https://github.com/istio/api/pull/870

**Comment by geeknoid** [comment]
Invitation sent. Welcome!

**Comment by idouba** [comment]
Thanks.
