### ISSUE TITLE
REQUEST: New membership for kramerul

### ISSUE THREAD

**Issue by kramerul** [istio/community#160]
If you'd like to become a member of the Istio organization on GitHub, please fill out this form and submit it.
Give us a few days to review and you should receive an invitation to join.

### GitHub user id
- kramerul

### Company affiliation
- SAP SE

### Requirements
- [X] I have reviewed the [community membership guidelines](https://github.com/istio/community/blob/master/ROLES.md#member)
- [X] I have reviewed the [contribution guidelines](https://github.com/istio/community/blob/master/CONTRIBUTING.md)
- [X] I have enabled [2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to [contributors](https://discuss.istio.io/c/contributors)

Provide a link to at least one PR that you have successfully pushed to one
of the Istio repos

* [#9090 Move everything related to spiffe URIs to package spiffe](https://github.com/istio/istio/pull/9090)
* [#8867 Move value identityDomain to global scope](https://github.com/istio/istio/pull/8867)
* [#8976 Allow identity domain to be configured in istio](https://github.com/istio/istio/pull/8976)
* [#9059 Add flag identityDomain to pilot.](https://github.com/istio/istio/pull/9059)
* [#9226 Allow identity domain to be configured in istio: Ensure e2e tests are working with different identity domain](https://github.com/istio/istio/pull/9226)
* [#11414 Add TCP tunnel integration test](https://github.com/istio/istio/pull/11414)

**Comment by geeknoid** [comment]
Invitation sent. Welcome!
