### ISSUE TITLE
REQUEST: New membership for tvieira

### ISSUE THREAD

**Issue by tvieira** [istio/community#173]
### GitHub user id
- tvieira

### Company affiliation
- Red Hat

### Requirements
- [x] I have reviewed the [community membership guidelines](https://github.com/istio/community/blob/master/ROLES.md#member)
- [x] I have reviewed the [contribution guidelines](https://github.com/istio/community/blob/master/CONTRIBUTING.md)
- [x] I have enabled [2FA on my GitHub account](https://github.com/settings/security)
- [x] I have subscribed to [contributors](https://discuss.istio.io/c/contributors)

Provide a link to at least one PR that you have successfully pushed to one
of the Istio repos

- Istio.io merged PRs (https://github.com/istio/istio.io/pulls?utf8=%E2%9C%93&q=is%3Apr+author%3Atvieira+is%3Amerged)
- istio PRs merged and open ones (https://github.com/istio/istio/pulls?utf8=%E2%9C%93&q=is%3Apr+author%3Atvieira)

**Comment by geeknoid** [comment]
Invitation sent. Welcome!
