### ISSUE TITLE
REQUEST: New membership for jkbschmid

### ISSUE THREAD

**Issue by jkbschmid** [istio/community#175]
### GitHub user id
- jkbschmid

### Company affiliation
- SAP SE

### Requirements
- [x] I have reviewed the [community membership guidelines](https://github.com/istio/community/blob/master/ROLES.md#member)
- [x] I have reviewed the [contribution guidelines](https://github.com/istio/community/blob/master/CONTRIBUTING.md)
- [x] I have enabled [2FA on my GitHub account](https://github.com/settings/security)
- [x] I have subscribed to [contributors](https://discuss.istio.io/c/contributors)

Provide a link to at least one PR that you have successfully pushed to one
of the Istio repos
Author:
- https://github.com/istio/istio/pull/13706
- https://github.com/istio/istio/pull/13395
- https://github.com/istio/installer/pull/29

**Comment by geeknoid** [comment]
Invitation sent. Welcome!
