### ISSUE TITLE
REQUEST: New membership for crazyxy

### ISSUE THREAD

**Issue by crazyxy** [istio/community#177]
If you'd like to become a member of the Istio organization on GitHub, please fill out this form and submit it.
Give us a few days to review and you should receive an invitation to join.

### GitHub user id
- crazyxy

### Company affiliation
- Google

### Requirements
- [x] I have reviewed the [community membership guidelines](https://github.com/istio/community/blob/master/ROLES.md#member)
- [x] I have reviewed the [contribution guidelines](https://github.com/istio/community/blob/master/CONTRIBUTING.md)
- [x] I have enabled [2FA on my GitHub account](https://github.com/settings/security)
- [x] I have joined the [Istio discussion board](https://discuss.istio.io) and subscribed to the [Contributors](https://discuss.istio.io/c/contributors) category
- [x] I have joined [Istio's Slack workspace](https://istio.slack.com) (fill-out this [form](https://docs.google.com/forms/d/e/1FAIpQLSfdsupDfOWBtNVvVvXED6ULxtR4UIsYGCH_cQcRr0VcG1ZqQQ/viewform) to join)

Provide a link to at least one PR that you have successfully pushed to one
of the Istio repos
- Merged pr 
  - https://github.com/istio/istio/pull/13529
  - https://github.com/istio/installer/pull/63
  - https://github.com/istio/istio/pull/13801
  - https://github.com/istio/istio/pull/13827
- Open pr
  - https://github.com/istio/istio/pull/13673
  - https://github.com/istio/istio/pull/13955
  - https://github.com/istio/installer/pull/146
  - https://github.com/istio/istio/pull/13974
- Contributed issue
  - https://github.com/istio/istio/issues/13014

**Comment by geeknoid** [comment]
Invitation sent. Welcome!
