### ISSUE TITLE
REQUEST: New membership for richardwxn

### ISSUE THREAD

**Issue by richardwxn** [istio/community#181]
If you'd like to become a member of the Istio organization on GitHub, please fill out this form and submit it.
Give us a few days to review and you should receive an invitation to join.

### GitHub user id
- richardwxn

### Company affiliation
- Google

### Requirements
- [x] I have reviewed the [community membership guidelines](https://github.com/istio/community/blob/master/ROLES.md#member)
- [x] I have reviewed the [contribution guidelines](https://github.com/istio/community/blob/master/CONTRIBUTING.md)
- [x] I have enabled [2FA on my GitHub account](https://github.com/settings/security)
- [x] I have joined the [Istio discussion board](https://discuss.istio.io) and subscribed to the [Contributors](https://discuss.istio.io/c/contributors) category
- [x] I have joined [Istio's Slack workspace](https://istio.slack.com) (fill-out this [form](https://docs.google.com/forms/d/e/1FAIpQLSfdsupDfOWBtNVvVvXED6ULxtR4UIsYGCH_cQcRr0VcG1ZqQQ/viewform) to join)

Provide a link to at least one PR that you have successfully pushed to one
of the Istio repos

[istio/installer#168](https://github.com/istio/installer/pull/168)
[istio/installer#150](https://github.com/istio/installer/pull/150)
[istio/installer#73](https://github.com/istio/installer/pull/73)
[istio/installer#90](https://github.com/istio/installer/pull/90)
[istio/istio#13560](https://github.com/istio/istio/pull/13560)

open:
[istio#13966](https://github.com/istio/istio/pull/13966)
[installer#132](https://github.com/istio/installer/pull/132)
[installer#104](https://github.com/istio/installer/pull/104)
[istio#13740](https://github.com/istio/istio/pull/13740)

**Comment by geeknoid** [comment]
Invitation sent. Welcome!
