### ISSUE TITLE
REQUEST: New membership for cgilmour

### ISSUE THREAD

**Issue by cgilmour** [istio/community#187]
### GitHub user id
- cgilmour

### Company affiliation
- Datadog

### Requirements
- [x] I have reviewed the [community membership guidelines](https://github.com/istio/community/blob/master/ROLES.md#member)
- [x] I have reviewed the [contribution guidelines](https://github.com/istio/community/blob/master/CONTRIBUTING.md)
- [x] I have enabled [2FA on my GitHub account](https://github.com/settings/security)
- [x] I have joined the [Istio discussion board](https://discuss.istio.io) and subscribed to the [Contributors](https://discuss.istio.io/c/contributors) category
- [x] I have joined [Istio's Slack workspace](https://istio.slack.com) (fill-out this [form](https://docs.google.com/forms/d/e/1FAIpQLSfdsupDfOWBtNVvVvXED6ULxtR4UIsYGCH_cQcRr0VcG1ZqQQ/viewform) to join)

Provide a link to at least one PR that you have successfully pushed to one
of the Istio repos

- https://github.com/istio/istio/pull/12687
- https://github.com/istio/istio/pull/13082

**Comment by geeknoid** [comment]
Invitation sent. Welcome!

**Comment by cgilmour** [comment]
That was quick. Thanks @geeknoid !
