### ISSUE TITLE
REQUEST: New membership for zhongfox

### ISSUE THREAD

**Issue by zhongfox** [istio/community#188]
If you'd like to become a member of the Istio organization on GitHub, please fill out this form and submit it.
Give us a few days to review and you should receive an invitation to join.

### GitHub user id
- zhongfox

### Company affiliation
- Tencent

### Requirements
- [x] I have reviewed the [community membership guidelines](https://github.com/istio/community/blob/master/ROLES.md#member)
- [x] I have reviewed the [contribution guidelines](https://github.com/istio/community/blob/master/CONTRIBUTING.md)
- [x] I have enabled [2FA on my GitHub account](https://github.com/settings/security)
- [x] I have joined the [Istio discussion board](https://discuss.istio.io) and subscribed to the [Contributors](https://discuss.istio.io/c/contributors) category
- [x] I have joined [Istio's Slack workspace](https://istio.slack.com) (fill-out this [form](https://docs.google.com/forms/d/e/1FAIpQLSfdsupDfOWBtNVvVvXED6ULxtR4UIsYGCH_cQcRr0VcG1ZqQQ/viewform) to join)

Provide a link to at least one PR that you have successfully pushed to one
of the Istio repos

* Merged pr
  * https://github.com/istio/istio/pull/14421
  * https://github.com/istio/api/pull/919

* closed issue:
  * https://github.com/istio/istio.io/issues/3861

* open issue:
  * https://github.com/istio/istio/issues/13468

**Comment by geeknoid** [comment]
Invitation sent. Welcome!
