### ISSUE TITLE
REQUEST: New membership for waynz0r

### ISSUE THREAD

**Issue by waynz0r** [istio/community#192]
If you'd like to become a member of the Istio organization on GitHub, please fill out this form and submit it.
Give us a few days to review and you should receive an invitation to join.

### GitHub user id
- waynz0r

### Company affiliation
- Banzai Cloud

### Requirements
- [x] I have reviewed the [community membership guidelines](https://github.com/istio/community/blob/master/ROLES.md#member)
- [x] I have reviewed the [contribution guidelines](https://github.com/istio/community/blob/master/CONTRIBUTING.md)
- [x] I have enabled [2FA on my GitHub account](https://github.com/settings/security)
- [x] I have joined the [Istio discussion board](https://discuss.istio.io) and subscribed to the [Contributors](https://discuss.istio.io/c/contributors) category
- [x] I have joined [Istio's Slack workspace](https://istio.slack.com) (fill-out this [form](https://docs.google.com/forms/d/e/1FAIpQLSfdsupDfOWBtNVvVvXED6ULxtR4UIsYGCH_cQcRr0VcG1ZqQQ/viewform) to join)

Provide a link to at least one PR that you have successfully pushed to one
of the Istio repos

**Comment by geeknoid** [comment]
Hi, 

Can you provide one or more links to PRs you've pushed into any of the Istio repos?

Thanks.

**Comment by waynz0r** [comment]
Hi @geeknoid,

Unfortunately, I can't atm. I work at Banzai Cloud, we would like to contribute to the official operator and @ostromart suggested that each of us should apply for membership by opening an issue here to be able to review PRs in the istio/operator repo.

Thanks!

**Comment by geeknoid** [comment]
Our official guidelines for membership as described in https://github.com/istio/community/blob/master/ROLES.md are that we need a PR in order to grant membership.  So I won't be able to grant you membership.

You can still review PRs, create issue, participate in issues, etc. But without membership, it will not be possible to assign anything to you.

Sorry about that.

**Comment by waynz0r** [comment]
Sure, no problem. I'll reopen the issue after a merged PR.
