### ISSUE TITLE
REQUEST: New membership for Laci21

### ISSUE THREAD

**Issue by Laci21** [istio/community#193]
If you'd like to become a member of the Istio organization on GitHub, please fill out this form and submit it.
Give us a few days to review and you should receive an invitation to join.

### GitHub user id
- Laci21

### Company affiliation
- [Banzai Cloud](https://banzaicloud.com/)

### Requirements
- [x] I have reviewed the [community membership guidelines](https://github.com/istio/community/blob/master/ROLES.md#member)
- [x] I have reviewed the [contribution guidelines](https://github.com/istio/community/blob/master/CONTRIBUTING.md)
- [x] I have enabled [2FA on my GitHub account](https://github.com/settings/security)
- [x] I have joined the [Istio discussion board](https://discuss.istio.io) and subscribed to the [Contributors](https://discuss.istio.io/c/contributors) category
- [x] I have joined [Istio's Slack workspace](https://istio.slack.com) (fill-out this [form](https://docs.google.com/forms/d/e/1FAIpQLSfdsupDfOWBtNVvVvXED6ULxtR4UIsYGCH_cQcRr0VcG1ZqQQ/viewform) to join)

Provide a link to at least one PR that you have successfully pushed to one
of the Istio repos

None yet. I'd like to contribute to the [Istio operator](https://github.com/istio/operator) repo. cc  @ostromart.

**Comment by geeknoid** [comment]
Hi there,

Before granting membership, we need to see a submitted PR in any of the Istio repos, as documented in https://github.com/istio/community/blob/master/ROLES.md.

Thanks.

**Comment by Laci21** [comment]
Hi @geeknoid,

Sure, I understand.

I actually submitted a tiny PR yesterday: https://github.com/istio/operator/pull/37, does this count? :)

If not, no problem, I'll submit another PR here as soon as I have one.

**Comment by geeknoid** [comment]
Please reopen when you've gotten some good PR in. Thanks.
