### ISSUE TITLE
REQUEST: New membership for fejta

### ISSUE THREAD

**Issue by fejta** [istio/community#195]
### GitHub user id
fejta

### Company affiliation
Google

### Requirements
- [x] I have reviewed the [community membership guidelines](https://github.com/istio/community/blob/master/ROLES.md#member)
- [x] I have reviewed the [contribution guidelines](https://github.com/istio/community/blob/master/CONTRIBUTING.md)
- [x] I have enabled [2FA on my GitHub account](https://github.com/settings/security)
- [x] I have joined the [Istio discussion board](https://discuss.istio.io) and subscribed to the [Contributors](https://discuss.istio.io/c/contributors) category
- [x] I have joined [Istio's Slack workspace](https://istio.slack.com) (fill-out this [form](https://docs.google.com/forms/d/e/1FAIpQLSfdsupDfOWBtNVvVvXED6ULxtR4UIsYGCH_cQcRr0VcG1ZqQQ/viewform) to join)

PRs: https://github.com/istio/test-infra/pull/1397#issuecomment-507430646

**Comment by duderino** [comment]
@fejta welcome to the sausage factory

**Comment by duderino** [comment]
And apparently I don't have the privs to merge so I've pinged @geeknoid to get this merged

**Comment by fejta** [comment]
Thanks!

**Comment by fejta** [comment]
BTW do we use [peribolos](https://github.com/kubernetes/test-infra/tree/master/prow/cmd/peribolos) to manage [org membership](https://github.com/kubernetes/org) and if not, do we want to?

**Comment by duderino** [comment]
@smawson just added you to the dev group.  @geeknoid normally handles these things but is on vacation.  He should answer the peribolos question

**Comment by fejta** [comment]
thanks!

**Comment by geeknoid** [comment]
Hi @fejta,

No, we don't use peribolos to manage org membership. I didn't know such a thing existed. What do you consider is the benefit of this additional piece of infra?

**Comment by fejta** [comment]
Provides an agreed upon source of Truth for who should be in the org and/or on a team. 

Provides an audit trail for changes (although this issue provides a lot of that). 

Allows delegating team construction to sub areas without giving them admin access to the org. 


It is by no means necessary but the kubernetes org has found it useful.

**Comment by fejta** [comment]
/close

Thanks for the invite
