### ISSUE TITLE
REQUEST: New membership for cjwagner

### ISSUE THREAD

**Issue by cjwagner** [istio/community#197]
### GitHub user id
- cjwagner

### Company affiliation
- Google

### Requirements
- [x] I have reviewed the [community membership guidelines](https://github.com/istio/community/blob/master/ROLES.md#member)
- [x] I have reviewed the [contribution guidelines](https://github.com/istio/community/blob/master/CONTRIBUTING.md)
- [x] I have enabled [2FA on my GitHub account](https://github.com/settings/security)
- [x] I have joined the [Istio discussion board](https://discuss.istio.io) and subscribed to the [Contributors](https://discuss.istio.io/c/contributors) category
- [x] I have joined [Istio's Slack workspace](https://istio.slack.com) (fill-out this [form](https://docs.google.com/forms/d/e/1FAIpQLSfdsupDfOWBtNVvVvXED6ULxtR4UIsYGCH_cQcRr0VcG1ZqQQ/viewform) to join)

> Provide a link to at least one PR that you have successfully pushed to one
of the Istio repos

I rebased Istio's Prow fork a while back. Not sure if that counts since it was in @sebastienvas' fork and some additional changes were force pushed: https://github.com/sebastienvas/k8s-test-infra/pull/3
I'll also be oncall starting tomorrow at noon PST so it would be helpful to be an org member in case anything comes up, but if this isn't sufficient it can probably wait until I make a PR to istio/test-infra.

**Comment by geeknoid** [comment]
Sorry, you need to submit an actual PR to the Istio org and have it merged before becoming a member.

Thanks.

**Comment by fejta** [comment]
/lgtm

Cole now has some PRs merged: https://github.com/istio/test-infra/pull/1428 https://github.com/istio/test-infra/pull/1427 https://github.com/istio/test-infra/pull/1426

Can we add him to the org now?

**Comment by geeknoid** [comment]
Invitation sent. Welcome!

**Comment by cjwagner** [comment]
Thanks!
