### ISSUE TITLE
Prow oncall needs admin access to istio for debugging purposes

### ISSUE THREAD

**Issue by fejta** [istio/community#198]
In order to properly support prow at least some members of the oncall team should have the ability to view Github's webhook logs for prow, for example it looks like there might be webhook issues but we have no way to debug this right now: https://github.com/istio/test-infra/issues/1452

a) who can access https://github.com/organizations/istio/settings/hooks?
b) what do the recent deliveries look like on the prow hook
c) can a subset of the oncall rotation get access to that page? who is the best people to make that call and grant that access?

/assign @smawson @rshriram @linsun 

Thanks!

**Comment by geeknoid** [comment]
The Istio TOC is the body  responsible for deciding who should get admin access and  tracking that.

In the meantime, I can help. From what I can tell, all deliveries to the webhook have been successful. Not all available events are being sent however, so perhaps some need to be added?

**Comment by fejta** [comment]
Can you make sure we have the following config:
* https://prow.istio.io/hook
* application/json
* Leave secret as it
* Enable SSL verification
* Send me everything
* Active. 

The missed hook would be around 4:11PM PST, often this requires clicking on the "load more deliveries" button... a) can you find the hook for this comment https://github.com/istio/test-infra/issues/1450#issue-466023533 and b) was it successful?

If so then we can try and debug into whether or not prow received it. If not, we can open a thread with Github support

**Comment by fejta** [comment]
Also who is on the TOC and what is the best to bring their attention to this request?

**Comment by geeknoid** [comment]
Info on the TOC: https://github.com/istio/community/blob/master/TECH-OVERSIGHT-COMMITTEE.md

Best way to get attention is to add to the agenda for the next meeting: https://docs.google.com/document/d/13lxJqtlaQhmV2EwsNnS6h-_O4pobZQZuMjrzOeMgVI0/edit#heading=h.o8pz6aqnzzgk

**Comment by geeknoid** [comment]
I can't find that event. I see 1449, but I don't see 1450. All deliveries are successful, there are no reported errors. 

As for the options, only selected events were being sent. I switched that to Send me everything. Let's see if that's enough to fix things.

**Comment by fejta** [comment]
Great thanks so much!! Also looked like we can capture more logging on our side anyway. Hopefully it was just a one off issue.

**Comment by fejta** [comment]
Let's delay this for now, will probably reopen at some point, but I think there's more we can do on our end re debugging first
/close
