### ISSUE TITLE
REQUEST: New membership for @clarketm

### ISSUE THREAD

**Issue by clarketm** [istio/community#212]
### GitHub user id
- @clarketm

### Company affiliation
- @google

### Requirements
- [x] I have reviewed the [community membership guidelines](https://github.com/istio/community/blob/master/ROLES.md#member)
- [x] I have reviewed the [contribution guidelines](https://github.com/istio/community/blob/master/CONTRIBUTING.md)
- [x] I have enabled [2FA on my GitHub account](https://github.com/settings/security)
- [x] I have joined the [Istio discussion board](https://discuss.istio.io) and subscribed to the [Contributors](https://discuss.istio.io/c/contributors) category
- [x] I have joined [Istio's Slack workspace](https://istio.slack.com) (fill-out this [form](https://docs.google.com/forms/d/e/1FAIpQLSfdsupDfOWBtNVvVvXED6ULxtR4UIsYGCH_cQcRr0VcG1ZqQQ/viewform) to join)

Provide a link to at least one PR that you have successfully pushed to one
of the Istio repos:

- istio/test-infra#1599
- Working on setting up internal Istio Prow instance.

**Comment by duderino** [comment]
/lgtm

Travis has joined Google's Istio EngProd team and will make lots of future contributions

**Comment by geeknoid** [comment]
Invitation sent. Welcome!
