### ISSUE TITLE
REQUEST: New membership for aattuluri

### ISSUE THREAD

**Issue by anilutcs** [istio/community#235]
If you'd like to become a member of the Istio organization on GitHub, please fill out this form and submit it.
Give us a few days to review and you should receive an invitation to join.

### GitHub user id
- aattuluri

### Company affiliation
- List your company name, or indicate Individual if you're not affiliated with a company
Intuit, Inc.

### Requirements
- [X] I have reviewed the [community membership guidelines](https://github.com/istio/community/blob/master/ROLES.md#member)
- [X] I have reviewed the [contribution guidelines](https://github.com/istio/community/blob/master/CONTRIBUTING.md)
- [X] I have enabled [2FA on my GitHub account](https://github.com/settings/security)
- [X] I have joined the [Istio discussion board](https://discuss.istio.io) and subscribed to the [Contributors](https://discuss.istio.io/c/contributors) category
- [X] I have joined [Istio's Slack workspace](https://istio.slack.com) (fill-out this [form](https://docs.google.com/forms/d/e/1FAIpQLSfdsupDfOWBtNVvVvXED6ULxtR4UIsYGCH_cQcRr0VcG1ZqQQ/viewform) to join)

Provide a link to at least one PR that you have successfully pushed to one
of the Istio repos
https://github.com/istio/istio/pull/18406
https://github.com/istio/istio/pull/11747
https://github.com/istio/istio/pull/11681

**Comment by geeknoid** [comment]
Invitation sent. Welcome!

**Comment by aattuluri** [comment]
@geeknoid 
I think you sent the invite to anilutcs, can you please resend it to **aattuluri**, this is the one I use. Let me know if I need to file an issue from that account. Sorry for the confusion.

**Comment by geeknoid** [comment]
All right, it's been resent.

**Comment by aattuluri** [comment]
@geeknoid Sorry, haven't received an invite. I double checked my email.

**Comment by geeknoid** [comment]
How about now?

**Comment by aattuluri** [comment]
Got it and joined, thanks!
