### ISSUE TITLE
REQUEST: New membership for yuxiaobo96

### ISSUE THREAD

**Issue by yuxiaobo96** [istio/community#236]
If you'd like to become a member of the Istio organization on GitHub, please fill out this form and submit it.
Give us a few days to review and you should receive an invitation to join.

### GitHub user id
- yuxiaobo96

### Company affiliation
- BoCloud

### Requirements
- [X] I have reviewed the [community membership guidelines](https://github.com/istio/community/blob/master/ROLES.md#member)
- [X] I have reviewed the [contribution guidelines](https://github.com/istio/community/blob/master/CONTRIBUTING.md)
- [X] I have enabled [2FA on my GitHub account](https://github.com/settings/security)
- [X] I have joined the [Istio discussion board](https://discuss.istio.io) and subscribed to the [Contributors](https://discuss.istio.io/c/contributors) category
- [X] I have joined [Istio's Slack workspace](https://istio.slack.com) (fill-out this [form](https://docs.google.com/forms/d/e/1FAIpQLSfdsupDfOWBtNVvVvXED6ULxtR4UIsYGCH_cQcRr0VcG1ZqQQ/viewform) to join)

Provide a link to at least one PR that you have successfully pushed to one
of the Istio repos

[istio/istio#18848](https://github.com/istio/istio/pull/18848)
[istio/istio.io#5329](https://github.com/istio/istio.io/pull/5329/files)
[istio/istio.io#5368](https://github.com/istio/istio.io/pull/5368/files)
[istio/istio.io#5374](https://github.com/istio/istio.io/pull/5374/files)

**Comment by geeknoid** [comment]
Invitation sent. Welcome!

**Comment by yuxiaobo96** [comment]
Thanks.

**Comment by yuxiaobo96** [comment]
@geeknoid 
Excuse me, I didn't receive an invitation in my mailbox.

**Comment by geeknoid** [comment]
How about now?

**Comment by yuxiaobo96** [comment]
@geeknoid 
Sorry, haven't received yet.
This is my email address:yuxiaobogo@163.com.

**Comment by yuxiaobo96** [comment]
In addition, I also linked a gmail: dis08315@gmail.com.

**Comment by yuxiaobo96** [comment]
I have received it.
Thank you!
