### ISSUE TITLE
REQUEST: New membership for hwdef

### ISSUE THREAD

**Issue by hwdef** [istio/community#239]
If you'd like to become a member of the Istio organization on GitHub, please fill out this form and submit it.
Give us a few days to review and you should receive an invitation to join.

### GitHub user id
- hwdef

### Company affiliation
- Individual

### Requirements
- [X] I have reviewed the [community membership guidelines](https://github.com/istio/community/blob/master/ROLES.md#member)
- [X] I have reviewed the [contribution guidelines](https://github.com/istio/community/blob/master/CONTRIBUTING.md)
- [X] I have enabled [2FA on my GitHub account](https://github.com/settings/security)
- [X] I have joined the [Istio discussion board](https://discuss.istio.io) and subscribed to the [Contributors](https://discuss.istio.io/c/contributors) category
- [X] I have joined [Istio's Slack workspace](https://istio.slack.com) (fill-out this [form](https://docs.google.com/forms/d/e/1FAIpQLSfdsupDfOWBtNVvVvXED6ULxtR4UIsYGCH_cQcRr0VcG1ZqQQ/viewform) to join)

Provide a link to at least one PR that you have successfully pushed to one
of the Istio repos

[istio/istio.io#5769](https://github.com/istio/istio.io/pull/5769)
[istio/istio#19031](https://github.com/istio/istio/pull/19031)
[istio/istio#17373](https://github.com/istio/istio/pull/17373)

I will continue to participate in the community and hope to make more contributions in the future!

**Comment by geeknoid** [comment]
Invitation sent. Welcome!
