### ISSUE TITLE
REQUEST: New membership for <helight>

### ISSUE THREAD

**Issue by helight** [istio/community#246]
If you'd like to become a member of the Istio organization on GitHub, please fill out this form and submit it.
Give us a few days to review and you should receive an invitation to join.

### GitHub user id
- helight

### Company affiliation
- tencent

### Requirements
- [x] I have reviewed the [community membership guidelines](https://github.com/istio/community/blob/master/ROLES.md#member)
- [x] I have reviewed the [contribution guidelines](https://github.com/istio/community/blob/master/CONTRIBUTING.md)
- [x] I have enabled [2FA on my GitHub account](https://github.com/settings/security)
- [x] I have joined the [Istio discussion board](https://discuss.istio.io) and subscribed to the [Contributors](https://discuss.istio.io/c/contributors) category
- [x] I have joined [Istio's Slack workspace](https://istio.slack.com) (fill-out this [form](https://docs.google.com/forms/d/e/1FAIpQLSfdsupDfOWBtNVvVvXED6ULxtR4UIsYGCH_cQcRr0VcG1ZqQQ/viewform) to join)
submit the join request and wait for approving.
Provide a link to at least one PR that you have successfully pushed to one
of the Istio repos

https://github.com/istio/istio/pull/19461
https://github.com/istio/istio.io/pull/6040
https://github.com/istio/istio.io/pull/6039
https://github.com/istio/istio/pull/19473
https://github.com/istio/istio.io/pull/6059
https://github.com/istio/istio.io/pull/6091
https://github.com/istio/istio/pull/19721

**Comment by helight** [comment]
@smawson could you help me to approve this. tks.

**Comment by helight** [comment]
@geeknoid could you help me to approve this. tks.

**Comment by smawson** [comment]
I'll take care of it.

**Comment by zehuaiWANG** [comment]
Thanks for @smawson to take care of this, @helight has been an excellent and consistent contributor to the istio. I think he should move up as an member.

**Comment by linsun** [comment]
invited, welcome @helight
