### ISSUE TITLE
REQUEST: New membership for <maplebeats>

### ISSUE THREAD

**Issue by maplebeats** [istio/community#247]
### GitHub user id
- maplebeats

### Company affiliation
- Tencent

### Requirements
- [x] I have reviewed the [community membership guidelines](https://github.com/istio/community/blob/master/ROLES.md#member)
- [x] I have reviewed the [contribution guidelines](https://github.com/istio/community/blob/master/CONTRIBUTING.md)
- [x] I have enabled [2FA on my GitHub account](https://github.com/settings/security)
- [x] I have joined the [Istio discussion board](https://discuss.istio.io) and subscribed to the [Contributors](https://discuss.istio.io/c/contributors) category
- [x] I have joined [Istio's Slack workspace](https://istio.slack.com) (fill-out this [form](https://docs.google.com/forms/d/e/1FAIpQLSfdsupDfOWBtNVvVvXED6ULxtR4UIsYGCH_cQcRr0VcG1ZqQQ/viewform) to join)

pr for istio tools:
https://github.com/istio/tools/pull/436

Provide a link to at least one PR that you have successfully pushed to one
of the Istio repos

**Comment by linsun** [comment]
approved, welcome @maplebeats
