### ISSUE TITLE
registry-1.docker.io server misbehaving

### ISSUE THREAD

**Issue by meelody** [istio/community#25]
I'm running a demo according to https://istio.io/docs/guides/bookinfo.html。My reviews-v1，reviews-v2，reviews-v3 are in the ErrImagePull state.   
 log  shows:"Warning  Failed                 1m (x3 over 3m)   kubelet, minikube  Failed to pull image "istio/examples-bookinfo-reviews-v2:0.2.8": rpc error: code = Unknown desc = Error response from daemon: Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on 192.168.64.1:53: server misbehaving".
How can I solve this  problem?

**Comment by ldemailly** [comment]
Seems like some transient issue with docker unrelated to istio ?

Also repo isn't for questions - emails to istio-users@ is typically the best for questions after you looked through
https://istio.io/help/
If you need to file an issue it should be in https://github.com/istio/issues/issues/
