### ISSUE TITLE
Migrate Slack signups to automated invitations

### ISSUE THREAD

**Issue by crcsmnky** [istio/community#251]
The current process for joining the [Istio Slack](https://istio.slack.com) requires users to complete a [Google Form](https://docs.google.com/forms/d/e/1FAIpQLSfdsupDfOWBtNVvVvXED6ULxtR4UIsYGCH_cQcRr0VcG1ZqQQ/viewform). The responses from that form are then manually collected and invitations are sent out from an existing member. 

This process is far too manual and there are other options out there. See the [Open Policy Agent Slack Signup](https://slack.openpolicyagent.org/). This is assembled using [slackin](https://github.com/rauchg/slackin).

I propose we spin up this app on Cloud Run to automate Istio Slack signup /cc @linsun @louiscryan @dcberg @smawson

**Comment by louiscryan** [comment]
Where are the email addresses logged ? We'd like to keep that information
accessible to steering committee.

**Comment by zehuaiWANG** [comment]
It sound good. cc @geeknoid

**Comment by crcsmnky** [comment]
The form responses are collected [here](https://docs.google.com/spreadsheets/d/1l23oStChCtBD8pF9qOM0ZMaaGbvQyiUM2BUoVwDAXVA/edit?usp=sharing). The doc should be visible to everyone in any of the Istio mailing lists.

**Comment by louiscryan** [comment]
... and they will continue to be collected there with this change ?

**Comment by crcsmnky** [comment]
Good question. The answer is **no**. They will not continue to be collected there. Using the slackin app linked above, there may be a way to continue logging the email addresses of folks who've signed up but that would require some custom integration with Sheets. Not impossible by any stretch of the imagination, but would be some work. 

Long term, I think we should go with the automated invite route, but to your point @louiscryan also log the email addresses just in case. 

Just like with other tooling, we should be able to do this in a manner that allows it be openly administered/operated by any of the responsible parties for other community tasks.

**Comment by louiscryan** [comment]
Couldn't we just set this up with an embedded script in the Google form ?

https://intoli.com/blog/make-a-public-slack-community/#create-a-google-form

**Comment by linsun** [comment]
I had thought users are *auto* invited to our slack after the form is filled.  If it is manual, I agree, we need to move to a more automated process.

**Comment by crcsmnky** [comment]
Great find! Yes, I can just implement that mechanism into the form/sheet. 

Sounds like @linsun and @louiscryan are in favor. Any other approvals needed or should I proceed with the integration?

**Comment by geeknoid** [comment]
Automation would be a great idea there. I had done this by hand for years since I wasn't smart enough to automate it :-)

**Comment by zehuaiWANG** [comment]
hi~ @geeknoid I found a github project maybe we can try: [slack-invite-automation](https://github.com/outsideris/slack-invite-automation)

**Comment by rvennam** [comment]
@craigbox I assume you will work on this automation? Meanwhile, who is doing the manual process?

**Comment by louiscryan** [comment]
Ram - The current process is automated.

???

**Comment by crcsmnky** [comment]
The current process is not automated, it is manual. Every morning I pull up the Slack signup spreadsheet that's backing the signup form and invite folks directly within Slack. All of which is why we need to automate the process. IIRC @craigbox is looking into how we can do this.

**Comment by craigbox** [comment]
As of a couple days ago, I now have access to the projects/certs/DNS
required to set up Slackin on slack.istio.io.   Just need to find time to
do it.

**Comment by louiscryan** [comment]
I'm sorry Sandeep - its easy to confuse magic and hard work.
