### ISSUE TITLE
REQUEST: New membership for nak3

### ISSUE THREAD

**Issue by nak3** [istio/community#255]
### GitHub user id
- nak3

### Company affiliation
- Red Hat

### Requirements
- [X] I have reviewed the [community membership guidelines](https://github.com/istio/community/blob/master/ROLES.md#member)
- [X] I have reviewed the [contribution guidelines](https://github.com/istio/community/blob/master/CONTRIBUTING.md)
- [X] I have enabled [2FA on my GitHub account](https://github.com/settings/security)
- [X] I have joined the [Istio discussion board](https://discuss.istio.io) and subscribed to the [Contributors](https://discuss.istio.io/c/contributors) category
- [X] I have joined [Istio's Slack workspace](https://istio.slack.com) (fill-out this [form](https://docs.google.com/forms/d/e/1FAIpQLSfdsupDfOWBtNVvVvXED6ULxtR4UIsYGCH_cQcRr0VcG1ZqQQ/viewform) to join)

Provide a link to at least one PR that you have successfully pushed to one
of the Istio repos

https://github.com/istio/istio/pull/19174
https://github.com/istio/istio/pull/19163
https://github.com/istio/istio/pull/19261
https://github.com/istio/istio/pull/19347
https://github.com/istio/istio/pull/19795

**Comment by craigbox** [comment]
Please create a PR as per https://github.com/istio/community/blob/master/ROLES.md#member.

**Comment by nak3** [comment]
Thank you @craigbox I opened https://github.com/istio/community/pull/277.

**Comment by linsun** [comment]
welcome @nak3
