### ISSUE TITLE
Running Istio on Docker for Mac with kubernetes

### ISSUE THREAD

**Issue by carlskii** [istio/community#27]
Hi I just installed Istio using Docker for Mac with kubernetes. Everything seems to be running, however  is running.  
<img width="1064" alt="istio" src="https://user-images.githubusercontent.com/555399/34833976-a6d098fe-f6e8-11e7-9fc4-5ca9c3db33a3.png">

However, my load-balancers external address is set to <pending>. Your documents reference accessing the application using the service NodePort, or use port-forwarding instead.

Please could you explain how to do this.

**Comment by ldemailly** [comment]
Issue moved to [istio/issues #161](https://github.com/istio/issues/issues/161) via [**ZenHub**](https://www.zenhub.com/)

**Comment by ldemailly** [comment]
This repo isn't for questions - emails to istio-users@ is typically the best for questions after you looked through
https://istio.io/help/
