### ISSUE TITLE
Will "ISTIO_MUTUAL" tls mode  still work between services deployed over two cluster with different root CA?

### ISSUE THREAD

**Issue by pramodrj07** [istio/community#273]
I have a replicated control plane setup and i am using different rootca than the common rootca that is suggested in the tutorial. However, I want to know which one of the scenarios below will work.

https://istio.io/docs/setup/install/multicluster/gateways/

1. Will the "ISTIO_MUTUAL" will work if I just provide the cacertificate (along with other standard credentials which istio demands) used to trust the service running on the other cluster?

Or

2. Do I have to expose the service through virtualservice and the provide cacertificate ?

OR 

3. Any other preferred method?

**Comment by craigbox** [comment]
Hi @pramodrj07 - please take this question to discuss.istio.io where it will get some attention.  This repo is for the administration of the Istio project infrastructure & governance.  Thanks!

**Comment by howardjohn** [comment]
Closing per ^
