### ISSUE TITLE
REQUEST: seperate istio.yaml into 2 files

### ISSUE THREAD

**Issue by linsun** [istio/community#286]
@howardjohn Thank you for all you do to make this process much easier now !   feedback: I found approving members need careful reviewing of which lines the members are added because if the PR adds in a wg lead or admin section, it can be pretty crazy.

Is it possible to separate istio.yaml into 2 files?  1 file for members and developers, the 2nd file for WG leads, maintainers and admin, etc?  This will reduce the chance of human approval errors.

**Comment by howardjohn** [comment]
@clarketm is this possible? I know k8s does it by org but I wasn't sure if we can split within an org

**Comment by clarketm** [comment]
> @clarketm is this possible? I know k8s does it by org but I wasn't sure if we can split within an org

As is, it does not appear [`peribolos`](https://github.com/kubernetes/test-infra/blob/d766f5c0c27cea83aefcbbeed9b79ab8b0da0225/prow/cmd/peribolos/main.go#L84) supports multiple config files. This feature can easily be add though.
