### ISSUE TITLE
Laravel FFMPEG Error Encoding Failed using Laravel Queue in Docker

### ISSUE THREAD

**Issue by UmarFarrooq** [istio/community#290]
I am running my laravel application on docker container.

i am using ffmpeg build https://johnvansickle.com/ffmpeg/releases/ffmpeg-release-amd64-static.tar.xz

i can confirm that ffmpeg and ffprobe are installed.

when i submit video to my application it is passed to a queue which is responsible to converts two version one is 720,1280 and other is 640, 360

what is happening at the moment . i am successfully able to convert uploaded file into 720,1280 but when it comes to convert 640,360 it throws Encoding Failed error.

i have switched conversion pattern like first i m trying to convert 640,360 then trying to convert 720,1280 . what have i noticed is that first conversion happens successfully , exception is always thrown at second conversion

here is my code sample

$format ->setKiloBitrate($bit_rate) ->setAudioChannels(2)->setAudioKiloBitrate(128);
$seven_twenty = new Dimension(1280, 720);
$video->filters()->resize($seven_twenty)->synchronize();
$video->save($format, $this -> Video['destination'].'-720-1281.mp4');

$format ->setKiloBitrate($bit_rate) -> setAudioChannels(2) -> setAudioKiloBitrate(128);
$three_sixty = new Dimension(640, 360);
$video->filters()->resize($three_sixty)->synchronize();
$video->save($format, $this -> Video['destination'].'-360-640.mp4');
can some one please help me on this.

thanks.

**Comment by clarketm** [comment]
@UmarFarrooq is this a Istio issue? Please file any Istio bugs or feature requests over in the [istio/istio](https://github.com/istio/istio/issues/new/choose) repository.

**Comment by howardjohn** [comment]
Closing per ^
