### ISSUE TITLE
Establish Working group community repo

### ISSUE THREAD

**Issue by sakshigoel12** [istio/community#3]
There is a lot of dummy text in this repo. 

Please could you work with each working group to start defining what makes sense to include in this repos. Thanks

**Comment by ldemailly** [comment]
should we delete the placeholder for now (eg https://github.com/istio/community/tree/master/core#description ) ? the WORKING-GROUP.md does have all the info for each group

cc @geeknoid

**Comment by geeknoid** [comment]
This is done.
