### ISSUE TITLE
REQUEST: new Istio team for infrastructure folks.

### ISSUE THREAD

**Issue by clarketm** [istio/community#300]
The group will consist of the [people](https://github.com/istio/test-infra/blob/cf50a19b06690dfa1e54209dae0837ea245da529/CODEOWNERS#L3) who maintain Prow and the various tools in [istio/test-infra](https://github.com/istio/test-infra). Alternatively, we could have these people join [WG - Test and Release](https://github.com/orgs/istio/teams/wg-test-and-release-maintainers).

**Comment by clarketm** [comment]
Either this is not the right place to make this request or no one cares.

**Comment by ericvn** [comment]
@clarketm For starting a new WG, I think you need to get on the TOC agenda. I know @fpesce just went through the process with a new WG, so not sure if there is something you should have done before approaching the TOC.

If you want the go via the Test and Release WG (my preferred thoughts), or maybe as a sub-group, then I would entertain getting on the agenda for that WG's meetings (every Tuesday at 11:30 Central). Francois and I are two of the leads in that WG.

**Comment by mandarjog** [comment]
@clarketm I think it makes sense to join the test and release group.
