### ISSUE TITLE
Community repo - can we remove the need of ok to test

### ISSUE THREAD

**Issue by linsun** [istio/community#326]
Seems ok to test is another manual step for us.  Is it really needed for community repo?  Can we remove it so all PRs are proceeded to testing phase?

**Comment by hzxuzhonghu** [comment]
I think this is to protect community CI infra and prevent malicious attackers from occupying all resources.

**Comment by sdake** [comment]
@hzxuzhonghu I think it is more about protecting CI credentials from being leaked. Or at least that used to be the last reason for this. On balance, I don't see the value as this is a roadblock to participation.

This is related: https://github.com/istio/community/issues/476

**Comment by linsun** [comment]
I think we have lots of discussions and decided we can't, closing this.
