### ISSUE TITLE
QPS for bookinfo application is limited

### ISSUE THREAD

**Issue by Cuiyus** [istio/community#337]
When I used istio to deploy the bookinfo application, I found that the maximum QPS of the application was 170. What caused this phenomenon?  (I have allocated sufficient resources for the 4 services in bookinfo）

**Comment by howardjohn** [comment]
This issue tracker is for Istio administrative tasks. For bugs on the product use istio/istio and for questions discuss.istio.io. can you move this?

however the bookinfo demo is meant for demos only, and is not in any way designed for high performance
