### ISSUE TITLE
Confusing protocol naming documentation 

### ISSUE THREAD

**Issue by igorbelianski** [istio/community#371]
I was reading page: 
 https://istio.io/latest/docs/ops/configuration/traffic-management/protocol-selection/#automatic-protocol-selection

specifically : 
The following protocols are supported:
 ...........
* `http`
* `http2`
* `https`
.............

Example below refers to protocol by   "http-web" 
  - number: 80
    name: http-web

the use of "-web" suffix is confusing : 
    can it be skipped ? ("http")
      is it mandatory for http2 and https as well

**Comment by howardjohn** [comment]
The suffix is documented: https://istio.io/latest/docs/ops/configuration/traffic-management/protocol-selection/#manual-protocol-selection

You can name it `http-foobar`, `http-my-favorite-port or just `http`.

This repo is for Istio community guidelines though, for bugs please file in github.com/istio/istio
