### ISSUE TITLE
auth docs have errors

### ISSUE THREAD

**Issue by Morriz** [istio/community#379]
https://istio.io/latest/docs/reference/config/security/request_authentication/

This doc has two errors:

- `hosts` should be a part of `operation`
- unescaped quote (go hunt)

**Comment by ericvn** [comment]
This page gets rendered from https://github.com/istio/api/blob/master/security/v1beta1/request_authentication.proto, and this issue could be moved to the istio/api repository.

**Comment by craigbox** [comment]
Both look fixed to me in the new version.  @Morriz could you confirm in https://istio.io/latest/docs/reference/config/security/request_authentication/ ?
