### ISSUE TITLE
Consider moving discussions to Github Discussions from discuss.istio.io

### ISSUE THREAD

**Issue by howardjohn** [istio/community#382]
See https://github.blog/2020-05-06-new-from-satellite-2020-github-codespaces-github-discussions-securing-code-in-private-repositories-and-more/

tl;dr discuss-like messaging board built into Github, in beta currently, GA by EOY.

**Comment by craigbox** [comment]
Added to Steering agenda.  Thanks!

**Comment by howardjohn** [comment]
@craigbox not sure what the steering conclusion was, but I think our org just got added to the beta or it went GA - either way, we are technically able to enable it if we choose to.

**Comment by linsun** [comment]
Think i have taken care of this?!  feel free to reopen if not.
