### ISSUE TITLE
Consider moving from Zenhub to Github projects

### ISSUE THREAD

**Issue by howardjohn** [istio/community#384]
https://docs.github.com/en/github/managing-your-work-on-github/about-project-boards

Motivation: Github projects is "first class" in github, so all users, even those without Zenhub installed, can have visibility into our priorities and devs modify them. This can all be done with a ~better~ native UI and APIs

Requirements:
* Projects meets our use case of assigning each issue a priority Release Blocker/P0/P1/P2, with easy project management (drag+drop) and milestone filtering
* All issue priorities can be migrated
* All tooling (policy bot) can be migrated to github projects

**Comment by incfly** [comment]
Has this been enabled already for Istio? We use Zenhub for team internal bug scrubbing, most features depend on this is priority, label filtering and assignee filtering.

**Comment by howardjohn** [comment]
@incfly that would fall under the first requirement that the projects meet our use case of doing this type of thing. Its not enabled currently, this is about exploring if we can do everything we do in zenhub, but with github projects
