### ISSUE TITLE
Open design docs to the public

### ISSUE THREAD

**Issue by bplotnick** [istio/community#388]
Currently the design docs are not publicly accessible and [require](https://github.com/istio/community/blob/master/CONTRIBUTING.md#design-documents) requesting membership of a google group. This is unusual for OSS in my experience, and is burden on the public - you wouldn't ask people to sign up to see the source code, right?

Please make these documents open to the public.

**Comment by ericvn** [comment]
@craigbox Is this satisfied now?

**Comment by craigbox** [comment]
It is!

There are probably still a few old links to folders that need to be updated, but all docs are now publicly readable.
