### ISSUE TITLE
Clarification needed on communication mechanisms for sub-groups of working groups

### ISSUE THREAD

**Issue by sdake** [istio/community#41]
I've been reading the governance documentation for Istio since the inception of this repository.

A few of us are interested (@baodongli, @gnirodi, @john-a-joyce, @sdake, possibly others) in forming a sub-group to a working group to focus on multicloud for 1.0 and hopefully land it in a usable form.

The question arises around these two clauses:
https://github.com/istio/community/blob/master/WORKING-GROUP-PROCESSES.md#be-open
https://github.com/istio/community/blob/master/WORKING-GROUP-PROCESSES.md#subgroups

The statement "We don’t formalize processes for subgroups, each working group can decide when subgroups are needed and how they operate" could be construed to mean that "should communicate primarily through the public working group meetings, through design documents in the working group’s folder, through GitHub issues, and GitHub PRs. Avoid private emails and/or meeting when possible." does not apply.

I believe it should, but the language in subgroups could use some clarification.

FWIW, my personal experiences have led me to believe ad-hoc video meetings (for sub-groups) that are not recorded slow down project velocity and reduces interest from other parties to participate.  I think that experience is probably captured in the be-open clause.  Certainly as we form this sub-group we do not want to do those things, nor violate Istio's governance.

Would someone mind providing clarification in the governance documentation?

**Comment by sdake** [comment]
cc @costinm Environments WG lead.

**Comment by costinm** [comment]
I'm a bit confused, not sure what you are looking for...

I agree that ad-hoc video meetings or private discussions are not the best,
and would prefer more communication
on the mailing list ( I'm not a big fan of slack either ). Do you have
proposals for a different forum or
would you want (recorded?) video meetings ? IMHO video meetings, even
recorded, don't work so
well for technical issues and don't scale very well.

Let's add this to the agenda for the next WG meeting - if the Environments
WG is not focused enough
on multicloud we need to fix it, and feedback and proposals are very
welcome ! As any open source
project, we depend on communication and contributions from members,
including for the agenda
and organization of the WG meetings and communication.

Costin

**Comment by sdake** [comment]
Agree re video meetings not working well for technical discussions and not scaling.  I think the current model works pretty well.

Perhaps we got a bit ahead of ourselves with talk of a subgroup without actually focusing on multicloud within the main workgroup (where communication channels are already setup) just as the multicloud work is getting off the ground.

The general problem remains with the governance documentation that those two clauses appear open to different (incompatible) interpretations.  Seeking clarified wording in the form a PR related to sub-groups, although that may not immediately be our issue to solve in the environments wg.

Cheers
-steve

**Comment by costinm** [comment]
On the 2 topics:

1. I think multicloud work is and should be the main focus of the Env WG,
and the work is already off the ground :-).
I am not very happy with the current communication - I would like to see
more participation and more emails from
more people in the community. If anyone has suggestions of better channels
- we can try. We do have pretty
healthy (IMO) technical discussions on the PR reviews ( sometimes a bit too
deep for a PR but still useful ) - and
it is clear that we have many motivated and smart people who want to help.


2. On the sub-groups topic - I think there is an implicit 'AND' between the
2 statements. Avoiding private
mails/meetings applies IMHO to any open source or community or standards
project. However avoiding
is not always possible, in particular between people on the same company or
working closely together,
but it still helps if notes are sent or discussed in the WG meeting or in a
github issue.
I think we already have few ad-hoc sub-groups of people who are more
focused on particular areas,
and it may be useful to have additional WG meetings on specific subject -
like the helm/install or
the new data model. However multicloud is IMHO too broad of a subject - and
almost everything
we do is in one way or another related to multicloud, or should take it
into consideration.
For example the new data structs are motivated in large part by the needs
of syncing large sets
and dealing with gateways, helm work is needed in part to handle the more
complicated needs when
setting up Istio in a diverse environment. I can't find work we do that is
not related to this.

Costin

**Comment by sdake** [comment]
Sounds fair @costinm.  Thanks for the insight.

Cheers
-steve
