### ISSUE TITLE
Nomination - Neeraj Poddar

### ISSUE THREAD

**Issue by nrjpoddar** [istio/community#424]
I nominate myself (@nrjpoddar) for the upcoming Steering Committee election

**Comment by nrjpoddar** [comment]
Feels really awkward self-nominating yourself..

**Comment by sdake** [comment]
@nrjpoddar fwiw, I don't have any good advice on this point. Many/most communities operate under self-nominations - it is more awkward having someone else nominate you and you are not interested 👍 

Cheers,
-steve
