### ISSUE TITLE
Nomination: Zack Butcher

### ISSUE THREAD

**Issue by zinuga** [istio/community#427]
I would like to nominate @ZackButcher for Istio steering.
- Affiliation: Tetrate
- Bio
Zack is contributor @IstioMesh and the founding engineer and Tetrate. Prior to Tetrate, he worked at Google as one of the core contributors to Istio. Prior to Istio he worked on a variety of teams across Google Cloud Platform, focusing on authorization, policy, data retention, and the internal system Istio draws from.

**Comment by linsun** [comment]
Thanks for the nomination, please submit a PR for this.  An example: https://github.com/istio/community/pull/425/files
