### ISSUE TITLE
Nomination: Jimmy Song

### ISSUE THREAD

**Issue by wu-sheng** [istio/community#428]
I would like to nominate @rootsongjc  for Istio steering.

- Affiliation: Tetrate
- Bio
Jimmy is a developer advocate at Tetrate, CNCF ambassador, co-founder of ServiceMesher Community which is the largest Service Mesh Community of the world with 4000+ members. He also writes blogs and books about Istio in the last few years. He has published five books on cloud native, four in translation, and one original.

**Comment by linsun** [comment]
Thanks for the nomination, please submit a PR for this.  An example: https://github.com/istio/community/pull/425/files

**Comment by wu-sheng** [comment]
Thanks, @linsun, Submitted.
