### ISSUE TITLE
steering committee info ?

### ISSUE THREAD

**Issue by ldemailly** [istio/community#44]
With the rename steering -> toc I think we lost a doc describing the new steering committee / the overall governance for istio ?

**Comment by thisisnotapril** [comment]
We did lost a doc for Steering, yes! I will get on spun up.

**Comment by ldemailly** [comment]
ping

**Comment by ldemailly** [comment]
ping x 2
@thisisnotapril

**Comment by geeknoid** [comment]
Done in #86
