### ISSUE TITLE
I want to vote 2020 Istio Steering Committee election guide, but I don't have receive any email

### ISSUE THREAD

**Issue by lyzhang1999** [istio/community#453]
how can I vote ?
link url: https://github.com/istio/community/tree/master/steering/elections/2020

**Comment by hzxuzhonghu** [comment]
https://github.com/istio/community/blob/master/steering/elections/2020/VOTERS.md

**Comment by lyzhang1999** [comment]
谢谢！

**Comment by craigbox** [comment]
Thanks for filling in the voter exception form; it requires a vote from Steering which I've asked for today.

**Comment by craigbox** [comment]
Approved; #458 updates voters and you'll get a ballot in the mail now.
