### ISSUE TITLE
For candidates, add a platform in addition to bio for next series of steering elections

### ISSUE THREAD

**Issue by sdake** [istio/community#456]
The existing Bio, while helpful, lacks detail.

I want to understand what each candidate wishes to do with their position in the elected steering committee.

I think it only fair to ask of people that want a seat at the steering table to disclose their objectives. From my 2019 Environments election, here is an example: https://discuss.istio.io/t/self-nomination-for-steven-dake-sdake/3833

In other governance patterns, a series of questions, defined by an election committee with input from the community must be answered before a nomination is accepted by the election officials. This is used in OpenStack, for example (and probably CNCF).

Cheers,
-steve

**Comment by craigbox** [comment]
Thanks for raising this Steve.  Sounds reasonable; Steering is on hiatus this week but I will raise it next week.

**Comment by craigbox** [comment]
Broad agreement that this will be a good thing.  I'll add it to the template for the next election.
