### ISSUE TITLE
Elaborate the diff between member and developer

### ISSUE THREAD

**Issue by hzxuzhonghu** [istio/community#476]
From here https://github.com/istio/community/blob/master/ROLES.md, I can not find the developer role.

**Comment by hzxuzhonghu** [comment]
cc @howardjohn @sdake  @istio/steering-committee

**Comment by howardjohn** [comment]
I suggest we just make everyone a developer once @brian-avery makes them have only `triager` permission

**Comment by craigbox** [comment]
SGTM as long as you use the word "member" throughout, as that's the usual term.  From what I can tell, it's just the name of a GitHub group?

**Comment by howardjohn** [comment]
There are two groups - developers (more access) and members (in the org but minimal/no access). So we would merge to a single group, "members" which have somewhere in the middle level of access, as we determined we do not want or need developers to have the access they have today.

**Comment by sdake** [comment]
Works for me. Who owns the technical work?

**Comment by craigbox** [comment]
@brian-avery Did you get a chance to look at this?

**Comment by brian-avery** [comment]
I looked into this, but at the time GitHub advertised two different sets of permission levels in their docs but only let you configure from the limited set. The Kubernetes tooling we use also only lets you use the limited set so would need to be extended.  Ideally, we would use triage for the majority of developers. However, I haven't tested setting it via the API.

**Comment by craigbox** [comment]
/cc zackzhangkai

Looks like members still need someone else to set /ok-to-test.

**Comment by brian-avery** [comment]
I have created https://github.com/kubernetes/test-infra/issues/21380 to update Peribolos to support the permission levels. The REST API seems like it supports everything we need to, but the GitHub documentation is inconsistent as to whether it supports it. Other issues have been pointing out these [inconsistencies](https://github.com/EclipseFdn/eclipsefdn-github-sync/issues/41#issuecomment-600800121) as well.

**Comment by craigbox** [comment]
Post-1.10 release bump, in case this is now back on the table.

**Comment by brian-avery** [comment]
This is still on the table. Right now we need a non-maintainer, non-lead volunteer to help us test.
