### ISSUE TITLE
Wrong bot action

### ISSUE THREAD

**Issue by daixiang0** [istio/community#486]
I have contributed some prs, see [here](https://github.com/istio/community/pull/383), while bot still consider me as new contributor [here](https://github.com/istio/istio/pull/28215#issuecomment-715038448), is it right？

**Comment by howardjohn** [comment]
I think you may be hitting the

> or it's been awhile since you've been here.

Part. After some number of days it will resend the message as a refresher

**Comment by daixiang0** [comment]
Get.

BTW, i am in member list, while my github role is contributor, is it normal?

**Comment by daixiang0** [comment]
@howardjohn hi, i am in the member list while i can not search myself by https://github.com/orgs/istio/people?query=daixiang0, is it normal?

**Comment by howardjohn** [comment]
Looks like You did not accept . should be an email from github

**Comment by daixiang0** [comment]
I do not find that, could you resend it?

**Comment by howardjohn** [comment]
I just did

**Comment by daixiang0** [comment]
Get, thanks.
