### ISSUE TITLE
Any port of pod can be connected if enabled envoy injection

### ISSUE THREAD

**Issue by Elven-coder** [istio/community#506]
We found that any port of pod can be connected after we enabled auto injection. Is this a bug?
<img width="425" alt="istio-1" src="https://user-images.githubusercontent.com/13388658/102440030-69ba8d80-405a-11eb-95de-7919a921222b.png">
<img width="439" alt="istio-2" src="https://user-images.githubusercontent.com/13388658/102440034-6aebba80-405a-11eb-8bfb-4340cfded8d6.png">
<img width="621" alt="istio-3" src="https://user-images.githubusercontent.com/13388658/102440038-6b845100-405a-11eb-8043-d537abf097af.png">

**Comment by howardjohn** [comment]
This repo is only for istio org/repo administistration, you can ask questions in https://discuss.istio.io/. Thanks!

But it is intended, we capture all traffic and envoy will accept the connection

**Comment by Elven-coder** [comment]
@howardjohn  Thanks a lot.
