### ISSUE TITLE
Transfer Istio trademark from Google to Open Usage Commons

### ISSUE THREAD

**Issue by ssuchter** [istio/community#521]
This issue is for tracking the status of the Istio trademark to the Open Usage Commons. (https://openusage.org/) Google announced this last year (https://istio.io/latest/blog/2020/open-usage/). The trademark registration is still unfinalized, and will transfer after finalization with the USPTO.

We can use this issue to track changes to this state.

**Comment by linsun** [comment]
Think this is no longer relevant
