### ISSUE TITLE
Documentation issue or Bug: Enabling egressgateway via documented methods does not create a deployment

### ISSUE THREAD

**Issue by asc-adean** [istio/community#526]
Referencing document: https://istio.io/latest/docs/tasks/traffic-management/egress/egress-gateway/#deploy-istio-egress-gateway

In this instance, I've performed an `istioctl install` with no arguments.  Later, I wanted to enable the egressgateway.  I followed the directions, and edited the IstioOperator according to the documentation.  This didn't appear to change anything, so I also ran the `istioctl` --set flags, which also appears to have no affect.

`kubectl get events -n istio-system` returns nothing

get all does not show any egressgateways:

```
$ k get all -n istio-system
NAME                                        READY   STATUS    RESTARTS   AGE
pod/istio-ingressgateway-5b69f56d57-lgvkl   1/1     Running   0          3d1h
pod/istiod-5cfb74fbfc-8sxws                 1/1     Running   0          3d1h

NAME                           TYPE           CLUSTER-IP     EXTERNAL-IP     PORT(S)                                                      AGE
service/istio-ingressgateway   LoadBalancer   10.72.31.109   xx.86.xx.101   15021:30749/TCP,80:32744/TCP,443:32254/TCP,15443:31496/TCP   3d1h
service/istiod                 ClusterIP      10.72.31.227   <none>          15010/TCP,15012/TCP,443/TCP,15014/TCP,853/TCP                3d1h

NAME                                   READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/istio-ingressgateway   1/1     1            1           3d1h
deployment.apps/istiod                 1/1     1            1           3d1h

NAME                                              DESIRED   CURRENT   READY   AGE
replicaset.apps/istio-ingressgateway-5b69f56d57   1         1         1       3d1h
replicaset.apps/istiod-5cfb74fbfc                 1         1         1       3d1h
```

Am I doing something wrong or does the documentation need adjusted?  Thanks

**Comment by kebe7jun** [comment]
hello @asc-adean , you should create an issue in https://github.com/istio/istio rather than here.

**Comment by GregHanson** [comment]
tested on latest 1.14.1 and verified the two install methods successfully deploy egress gateway

**Comment by linsun** [comment]
Thanks Greg!  @asc-adean can you please retry?  and reopen in istio/istio if you still see this prob.
