### ISSUE TITLE
Integrating an existing service mesh like envoy with Istio

### ISSUE THREAD

**Issue by tianxiaoliang** [istio/community#53]
M plaing to integrate my own service mesh with Istio, and hoping to contribute Istio code and guide about how to integrate with Istio during the integration.

here is some clues I found
**Pilot send standard format information to envoy, so first I need to impement data plane API**
https://www.envoyproxy.io/docs/envoy/latest/configuration/overview/v2_overview#rest-endpoints
it includes both grpc and rest, my question is which kind of transport pilot use to access data plane API

after I install my service mesh into env like k8s how Istio discovery service mesh? a specific port for each of service in service registry?

**Comment by ldemailly** [comment]
can you ask your question on https://groups.google.com/forum/#!forum/istio-users

thanks
