### ISSUE TITLE
Istio. How to add Virtual Host to Envoy?

### ISSUE THREAD

**Issue by StanislavMakhrov** [istio/community#563]
Using Istio EnvoyFilter https://istio.io/latest/docs/reference/config/networking/envoy-filter/ I want to add new VirtualHost inside Envoy in sidecar of pods.
How to do this?

I guess I should create and apply manifest something like:

    apiVersion: networking.istio.io/v1alpha3
    kind: EnvoyFilter
    metadata:
      name: my-filter
      namespace: default
    spec:
      workloadSelector:
        labels:
          run: mylabel
      configPatches:
      - applyTo: ???
        match:
          context: SIDECAR
        patch:
          operation: ADD
          value:
            ???

**Comment by craigbox** [comment]
Hi @StanislavMakhrov !

We don't use this repository for project support. Please feel free to ask your question on our support forum, https://discuss.istio.io/, if it's still an issue.
