### ISSUE TITLE
How to configure custom rate limits per user type?

### ISSUE THREAD

**Issue by Algirdyz** [istio/community#571]
I'm looking into potential kubernetes ingress solutions out there, but we have a lot of requirements.
There's one of them I couldn't really figure out how to do or if it's possible right now.

I would like to rate limit certain api paths based on a type of user that made the request.
So a user includes a token in their http request header and calls an API. Using that token I would like to retrieve the limits for that particular user and apply them. This retrieval would be a call to a redis Database. Retrieved data could be an envoy rate limit descriptor that is sent to a gRPC service which has the limits are set.

Is this possible to achieve? Could this functionality be configured in a different way than I described?

**Comment by craigbox** [comment]
Hi @Algirdyz 

We don't use this repository for project support. Please feel free to ask your question on our support forum, https://discuss.istio.io/, if it's still an issue.  (I know we're working on new APIs for rate limiting, but until then you can use EnvoyFilter.)
