### ISSUE TITLE
TLS passthrough sample: SSL_CTX_use_certificate:ca md too weak

### ISSUE THREAD

**Issue by Morriz** [istio/community#573]
When following these docs: https://istio.io/latest/docs/tasks/traffic-management/ingress/ingress-sni-passthrough/

I get errors that the generated cert for CA is created using a too weak algorithm:

```
2021/05/26 22:43:57 [emerg] 1#1: SSL_CTX_use_certificate("/etc/nginx-server-certs/tls.crt") failed (SSL: error:140AB18E:SSL routines:SSL_CTX_use_certificate:ca md too weak)                                                                               │
│ nginx: [emerg] SSL_CTX_use_certificate("/etc/nginx-server-certs/tls.crt") failed (SSL: error:140AB18E:SSL routines:SSL_CTX_use_certificate:ca md too weak)
```

**Comment by Morriz** [comment]
I'm using openssl 1.1 on OSX btw

**Comment by Morriz** [comment]
if you add one extra param to each of the 3 openssl commands it will pass on modern k8s clusters: `-sha256`

**Comment by craigbox** [comment]
Thanks, I see that parameter is included in the docs now!
