### ISSUE TITLE
missing in 'kinds' of kubernetes account configuration

### ISSUE THREAD

**Issue by hmallepally** [istio/community#574]
we suddenly started getting this error on spinnaker .

any hints here?  we are providing service account for deployments and virtual service uses that right? do we need to do anything special here?

```
Exception ( Deploy Manifest )
deployKubernetesManifest.deployKubernetesManifest.VirtualService.networking.istio.io.Kind [VirtualService.networking.istio.io] missing in 'kinds' of kubernetes account configuration

```

**Comment by craigbox** [comment]
Hi @hmallepally !

We don't use this repository for project support. Please feel free to ask your question on our support forum, https://discuss.istio.io/, if it's still an issue.
