### ISSUE TITLE
REQUEST: New membership for yonicurv

### ISSUE THREAD

**Issue by yonicurv** [istio/community#575]
Hello,

As we are using at our company Istio implementation.
I would be happy to join the community as a member.

Please let me know if any special actions are required to become a memner.

Thanks,
Jonathan.

**Comment by kebe7jun** [comment]
@yonicurv please see: https://github.com/istio/community/blob/master/ROLES.md#member

**Comment by craigbox** [comment]
Jonathan - thanks for your interest in Istio.  Please open a PR as per kebe's link when you're ready!
