### ISSUE TITLE
 istioctl  install Unauthenticated error

### ISSUE THREAD

**Issue by cc20110101** [istio/community#584]
istio 1.10.0 
k8s 1.20.7

./istioctl  install

istio-ingressgateway pod error:
![image](https://user-images.githubusercontent.com/12064991/121332703-b2d50580-c94a-11eb-83fa-2750c927e4d3.png)

![image](https://user-images.githubusercontent.com/12064991/121333027-fdef1880-c94a-11eb-8a3b-53101d512695.png)

**Comment by howardjohn** [comment]
Take a look at istiod logs, it will indicate why it failed to authenticate

**Comment by cc20110101** [comment]
[root@k8s-master1 ~]# kubectl logs -n istio-system istiod-79dd646bcd-dqsm4 -f

2021-06-10T01:02:20.943082Z     warn    serverca        Authentication failed for 10.244.159.129:53156: Authenticator ClientCertAuthenticator at index 0 got error: no verified chain is found. Authenticator KubeJWTAuthenticator at index 1 got error: failed to validate the JWT from cluster "Kubernetes": the service account authentication returns an error: [invalid bearer token, square/go-jose: error in cryptographic primitive].

**Comment by sgLancelot** [comment]
Hi, I am facing the exact same issue.

istio 1.10.0
k8s 1.20.7

My istio proxy sidecars are generating those errors in the original post, and their readiness probe is constantly failing. My istiod logs are also showing the same "[invalid bearer token, square/go-jose: error in cryptographic primitive]" errors for pods that have issues.

I notice that the moment I do a rollout restart of the istiod deployment, the proxy sidecar will recover within seconds, with the readiness passing health check. Checking the sidecar logs will show that it generated new workload certificate, detected the root cert has changed and start rotating the root cert.

struggling with this for a couple of days now.

**Comment by aswathysdn** [comment]
Hi @howardjohn , we are facing the same issue as above. can you please provide any pointers?

**Comment by craigbox** [comment]
It looks like your Kubernetes nodes need their certs regenerated.
https://github.com/kubernetes/kubernetes/issues/110035

I don't think tis is Istio-specific, so I'm closing the issue.  If you have ongoing problems, please check out https://discuss.istio.io/.

**Comment by cc20110101** [comment]
Didn't solve the problem. I won't use isio for the time being
