### ISSUE TITLE
Calendar invite links for the working groups are not working

### ISSUE THREAD

**Issue by tvieira** [istio/community#66]
Almost all calendar invites in the WORKING-GROUPS.md file. The error message I get is:

 "Could not find event requested"

**Comment by sdake** [comment]
@tvieira - one thing you might try is to subscribe to the istio-dev mailing list.  https://groups.google.com/forum/#!forum/istio-dev

If the calendar works after that, could you report back so we can get it fixed either in the docs or in the ACLs on the calendar?

Cheers
-steve

**Comment by tvieira** [comment]
@sdake - I am subscribed to the majority of the mailing lists, including istio-dev.

**Comment by sdake** [comment]
@tvieira ok - I'm out of ideas then :)

**Comment by tvieira** [comment]
Pull #67 removed all the calendar links. So I'm closing this issue as it has now been resolved.
