### ISSUE TITLE
Where can I propose a change to istio helm so services can accept annotations? 

### ISSUE THREAD

**Issue by klustria** [istio/community#68]
Currently, Istio installation defaults to creating LoadBalancer for ingress, ingress-gateway, and tracing. Most providers allow annotations to change the shape of LoadBalancers. I have a change that allows adding annotations to mentioned services so users can have the flexibility to use other LoadBalancer shapes that the provider supports. Please let me know how to contribute my change and if I need to create a PR to make this happen. Would appreciate if you can point me to the right channel that handles helm maintenance for further discussion on this.

**Comment by klustria** [comment]
Please ignore, I checked the latest code and it seemed to have been implemented already. Furthermore, I also think this is the wrong place to file this and I apologize for that. Closing this now.

**Comment by ldemailly** [comment]
also for the future the repo to file issues is istio/istio - this repo issues would be about bug or issue in the community documents, not istio code

**Comment by klustria** [comment]
Yeah, I apologize as I thought I was filing in istio/istio. As a question though, isn't helm part of the code?

**Comment by ldemailly** [comment]
yes helm is part of the code so if you still have that concern open an issue there
