### ISSUE TITLE
Configure Envoy through the Istio GW/VS

### ISSUE THREAD

**Issue by ep4sh** [istio/community#704]
Dear community,

could you please guide me if there is a magic way to configure the Envoy settings via resources like Gateway or Virtual service?
I need such capability to allow my end users to apply desired settings via the GW/VS ( a bit more flexible than applying such settings globally).

Applying the WASM plugin could be an option but I didn’t find a way to configure it non-globally.

Ps. I can’t use the Envoy filter due to the security restrictions.

Really appreciate any suggestion.

Cheerz,
Pasha

**Comment by ep4sh** [comment]
Hi @GregHanson, thank you for reply, I think I still need to have such capability to configure any Envoy settings from the docs, since I would like to provide such settings as configuration interface and make some test/limits on these settings. 
I hope it was clear, please let me know :)

Regards, 
Pasha

**Comment by craigbox** [comment]
Hi @ep4sh!

We don't use this repository for project support. Please feel free to ask your question on our support forum, https://discuss.istio.io/, if it's still an issue.

**Comment by craigbox** [comment]
The method for configuring arbitrary settings in Envoy is EnvoyFilter; I don't believe we plan to expose any other method.  We're instead working on our own APIs like the Telemetry API.
