### ISSUE TITLE
excludeOutboundIPRanges

### ISSUE THREAD

**Issue by chengjun0124** [istio/community#722]
Hi team

I used `traffic.sidecar.istio.io/excludeOutboundIPRanges` in istio 1.4, my initContainer can access network. But after upgrading to istio 1.9, it doesn't wok, my initContainer can't access network.

**Comment by chengjun0124** [comment]
Could anyone help on this?

**Comment by chengjun0124** [comment]
@craigbox

**Comment by craigbox** [comment]
Hi @chengjun0124, this repo isn't for support issues.  I suggest you try https://discuss.istio.io, or, if you think it's a bug in Istio, raise an issue in istio/istio.

Thanks and good luck!

**Comment by chengjun0124** [comment]
Thank you.
