### ISSUE TITLE
Applying for Istio membership

### ISSUE THREAD

**Issue by stewart-yu** [istio/community#78]
### GitHub user id
- stewart-yu

### Company affiliation
- Huawei Technologies Co., Ltd. China

### Requirements
- [x] I have reviewed the [community membership guidelines](https://github.com/istio/community/blob/master/ROLES.md#member)
- [x] I have reviewed the [contribution guidelines](https://github.com/istio/community/blob/master/CONTRIBUTING.md)
- [x] I have enabled [2FA on my GitHub account](https://github.com/settings/security)
- [x] I have subscribed to the [istio-dev@](https://groups.google.com/forum/#!forum/istio-dev) mailing list
- [x] I have made multiple contributions to the project or community. Contributions may include, but are not limited to:
    - Authoring or reviewing PRs on GitHub
    - Filing or commenting on issues on GitHub
    - Contributing to working group or community discussions
- [x] I have two sponsors that meet the sponsorship requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### List of sponsors
- @GregHanson
- @linsun 
- @ayj
- @sdake 

### List of contributions to the Istio project
- PRs reviewed

- PRs authored
[https://github.com/istio/istio/pull/8174](https://github.com/istio/istio/pull/8174)
[https://github.com/istio/istio/pull/8206](https://github.com/istio/istio/pull/8206)
[https://github.com/istio/istio/pull/8304](https://github.com/istio/istio/pull/8304)
[https://github.com/istio/istio/pull/8514](https://github.com/istio/istio/pull/8514)
[https://github.com/istio/istio/pull/8567](https://github.com/istio/istio/pull/8567)
[https://github.com/istio/istio/pull/8570](https://github.com/istio/istio/pull/8570)
[https://github.com/istio/istio/pull/8680](https://github.com/istio/istio/pull/8680)
[https://github.com/istio/istio/pull/8706](https://github.com/istio/istio/pull/8706)
[https://github.com/istio/istio/pull/8711](https://github.com/istio/istio/pull/8711)
[https://github.com/istio/istio/pull/8737](https://github.com/istio/istio/pull/8737) 
[https://github.com/istio/istio/pull/8752](https://github.com/istio/istio/pull/8752)
[https://github.com/istio/istio/pull/8758](https://github.com/istio/istio/pull/8758)
[https://github.com/istio/istio/pull/8766](https://github.com/istio/istio/pull/8766)

- Issues responded to
[https://github.com/istio/istio/issues/8508](https://github.com/istio/istio/issues/8508)
[https://github.com/istio/istio/issues/8568](https://github.com/istio/istio/issues/8568)
 
- Workgroup(s) I am involved with
```
Test, Mixer
```

### Slack access
-  yuchuanjian@huawei.com

**Comment by sdake** [comment]
@stewart-yu looks fine to me, although I am waiting on TOC feedback on sponsor expectations before I can commit to sponsoring.  Thanks for understanding @stewart-yu - we should have this red tape sorted out by friday :)

Cheers
-streve

**Comment by hzxuzhonghu** [comment]
+1

**Comment by sdake** [comment]
I have spoken with Stewart about mentorship towards becoming a member and have agreed to guide him.  The commits look great from @stewart-yu, but would like to see some review participation and wg participation (if viable).  The delineation of reviewed vs authored PRs is also confusing in this new member request.  Every linked PR appears to be original PRs from @stewart-yu rather than any specific review of someone else's work from @stewart-yu.

Cheers
-steve

**Comment by sdake** [comment]
@stewart-yu the application looks much better now.  Thank you for editing the confusion away :).  I'd be willing to sponsor given the updated application.  I would still recommend involvement in a workgroup as well as reviewing if those activities are viable for you.

/lgtm

**Comment by stewart-yu** [comment]
Thanks, :+1:  @sdake 
Add `Test` SIG, for more contribution in CI before. Such as 

1. add `spelling_check.sh` in CI [https://github.com/istio/istio/pull/8514](https://github.com/istio/istio/pull/8514), for saw many PR about `fix type`;
2. fix shell-check in CI[https://github.com/istio/istio/pull/8706](https://github.com/istio/istio/pull/8706);
3. fix codecov in CI [https://github.com/istio/istio/issues/8568](https://github.com/istio/istio/issues/8568)

and add `Mixer` SIG for interesting now.
Next time, will add some content in `PRs reviewed` section.

**Comment by louiscryan** [comment]
Approved by TOC
