### ISSUE TITLE
Istio feeds not working in feeder

### ISSUE THREAD

**Issue by vinay01tech** [istio/community#789]
Hi Team,

I am not able to add feeds into feeder.

1. https://istio.io/latest/blog/feed.xml --> this works
2. https://istio.io/latest/news/feed.xml and https://istio.io/latest/feed.xml won't work.

I am trying to add them into feeder

Thanks
Vinay

**Comment by vinay01tech** [comment]
I am using the feeder extension in the firefox browser, I am getting this issue for a long time.

**Comment by craigbox** [comment]
Hi Vinay,

They all look to validate according to https://validator.w3.org/feed/.  Can you give any more insight into what happens when you try?  Are there any errors in the Firefox console?

**Comment by craigbox** [comment]
Please feel free to re-open if you find a way to reproduce.
