### ISSUE TITLE
Get into cncf/devstats

### ISSUE THREAD

**Issue by craigbox** [istio/community#809]
Move from https://istio.teststats.cncf.io/ to https://istio.devstats.cncf.io/.

**Comment by craigbox** [comment]
https://github.com/cncf/devstats/issues/373

**Comment by ericvn** [comment]
It looks like this is completed.

**Comment by zirain** [comment]
nop, devstats do not updated 

![image](https://user-images.githubusercontent.com/4354057/195742244-ad8246b8-a493-4b3d-82ce-5312b4d23efe.png)

**Comment by ericvn** [comment]
Interesting. Originally devstats wasn't there and that is now. I hadn't made any number comparisons.

**Comment by zirain** [comment]
> Interesting. Originally devstats wasn't there and that is now. I hadn't made any number comparisons.

After double check, devstats data is ok, data updated a little later than tesstats. seems like job is not running at the same time.
we can close this.

**Comment by ericvn** [comment]
Was going to look into changing the icon for Istio to ours. Seems to be a default CNCF one the last I looked.

**Comment by craigbox** [comment]
It's the sailboat now!
