### ISSUE TITLE
How to globally disable HTTP retries on Virtual Services

### ISSUE THREAD

**Issue by thatguyatgithub** [istio/community#838]
Hi, we have found that the default policy about failing envoy requests is to retry twice after a given timeout period, as its well detailed on the documentation here https://istio.io/latest/docs/concepts/traffic-management/#retries.
```
The default retry behavior for HTTP requests is to retry twice before returning the error.
```

We were trying to disable it globally everywhere because particularly for us, it's introducing some inconsistencies  on HTTP POST operations that alter the nature of the object, generating some inconsistency issues.

We were unable to find a way to disable HTTP connection retries globally in a way that does not imply creating VirtualService on a per-service basis, which will add a lot of complexity for us.

Can you help us confirm that there is no way to instruct Istio not to perform any kind of connection retries at HTTP globally?

**Comment by howardjohn** [comment]
Its part of
https://istio.io/latest/docs/reference/config/istio.mesh.v1alpha1/#MeshConfig

**Comment by thatguyatgithub** [comment]
You are totally correct, I've applied it and it's working as expected, thanks a lot!
