### ISSUE TITLE
REQUEST: New membership for jsenon

### ISSUE THREAD

**Issue by jsenon** [istio/community#85]
### GitHub user id
- 15340544

### Company affiliation
- Individual

### Requirements
- [x] I have reviewed the [community membership guidelines](https://github.com/istio/community/blob/master/ROLES.md#member)
- [x] I have reviewed the [contribution guidelines](https://github.com/istio/community/blob/master/CONTRIBUTING.md)
- [x] I have enabled [2FA on my GitHub account](https://github.com/settings/security)
- [x] I have subscribed to the [istio-dev@](https://groups.google.com/forum/#!forum/istio-dev) mailing list
- [x] I have made multiple contributions to the project or community. Contributions may include, but are not limited to:
    - Authoring or reviewing PRs on GitHub
    - Filing or commenting on issues on GitHub
    - Contributing to working group or community discussions
- [x] I have two sponsors that meet the sponsorship requirements listed in the community membership guidelines.  Sponsor requirements:
    - Sponsors must have close interactions with the prospective member - e.g. code/design/proposal review, coordinating on issues, etc.
    - Sponsors must be reviewers or approvers in at least 1 OWNERS file (in any repo in the Istio GitHub organization)
    - Sponsors must be from multiple member companies to demonstrate integration across community.
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### List of sponsors
- @geeknoid 
- @rshriram 

### List of contributions to the Istio project
- PRs authored: #2332, #2322, #1393, #1392, #1175, #1165, #1092
- Issues responded to #6071, #388, #886
- Meetup Presentation done: DevOps Meetup Toulouse
- Group: Istio Environments, Istio Performance and Scalability, Istio Test & Release Group
- Participate to Community testing

### Slack access
- julien.senon@gmail.com

**Comment by rshriram** [comment]
Lgtm

**Comment by thisisnotapril** [comment]
Is there a timeline given for requests to be reviewed and approved?

**Comment by linsun** [comment]
we forgot to review it in the last friday's TOC mtg.  We'll make sure this gets reviewed this Friday.

**Comment by louiscryan** [comment]
Approved by TOC
