### ISSUE TITLE
REQUEST: New membership for jmazzitelli

### ISSUE THREAD

**Issue by jmazzitelli** [istio/community#91]
### GitHub user id
- jmazzitelli

### Company affiliation
- Red Hat, Inc.

### Requirements
- [x] I have reviewed the [community membership guidelines](https://github.com/istio/community/blob/master/ROLES.md#member)
- [x] I have reviewed the [contribution guidelines](https://github.com/istio/community/blob/master/CONTRIBUTING.md)
- [x] I have enabled [2FA on my GitHub account](https://github.com/settings/security)
- [x] I have subscribed to the [istio-dev@](https://groups.google.com/forum/#!forum/istio-dev) mailing list
- [x] I have made multiple contributions to the project or community. Contributions may include, but are not limited to:
    - Authoring or reviewing PRs on GitHub
    - Filing or commenting on issues on GitHub
    - Contributing to working group or community discussions
- [x] I have two sponsors that meet the sponsorship requirements listed in the [community roles](./ROLES/#sponsor].
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### List of sponsors
- @douglas-reid (Google)
- @gbaufake (Red Hat)
- @jeffmendoza (Google)
- @gyliu513 (IBM)

### List of contributions to the Istio project
- PRs reviewed
- PRs authored
  - https://github.com/istio/istio.io/pull/2190
  - List of Istio PRs: https://github.com/istio/istio/pulls?q=is%3Apr+author%3Ajmazzitelli+
- Issues responded to
  - List of Istio issues: https://github.com/istio/istio/issues?q=is%3Aissue+mentions%3Ajmazzitelli+
- Workgroup(s) I am involved with
  - Policies and Telemetry

### Slack access
- If you'd like to join our developer Slack workspace, what is the email address you have associated with Slack?
  - I do not want to set this up yet

**Comment by gbaufake** [comment]
+1 on accepting @jmazzitelli

**Comment by gyliu513** [comment]
+1 as well, thanks @jmazzitelli for your contribution!

**Comment by louiscryan** [comment]
Approved by TOC
