### ISSUE TITLE
REQUEST: New membership for x15zhang

### ISSUE THREAD

**Issue by x15zhang** [istio/community#92]
### GitHub user id
- x15zhang

### Company affiliation
- Huawei Technologies Co., Ltd. China

### Requirements
- [x] I have reviewed the [community membership guidelines](https://github.com/istio/community/blob/master/ROLES.md#member)
- [x] I have reviewed the [contribution guidelines](https://github.com/istio/community/blob/master/CONTRIBUTING.md)
- [x] I have enabled [2FA on my GitHub account](https://github.com/settings/security)
- [x] I have subscribed to the [istio-dev@](https://groups.google.com/forum/#!forum/istio-dev) mailing list
- [x] I have made multiple contributions to the project or community. Contributions may include, but are not limited to:
    - Authoring or reviewing PRs on GitHub
    - Filing or commenting on issues on GitHub
    - Contributing to working group or community discussions
- [x] I have two sponsors that meet the sponsorship requirements listed in the [community roles](./ROLES/#sponsor].
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### List of sponsors
- @rshriram
- @linsun
- @m1093782566

### List of contributions to the Istio project
- PRs reviewed
  [istio/istio#6081](https://github.com/istio/istio/pull/6081)
- PRs authored
  [istio/istio#7801](https://github.com/istio/istio/pull/7801)
  [istio/api#550](https://github.com/istio/api/pull/550)
  [istio/api#522](https://github.com/istio/api/pull/522)
  [istio/community#90](https://github.com/istio/community/pull/90)  
- Issues responded to
  [istio/istio#6070](https://github.com/istio/istio/issues/6070)
  [istio/istio#9051](https://github.com/istio/istio/issues/9051)  
  [istio/istio#8767](https://github.com/istio/istio/issues/8767)  
  [istio/istio#8572](https://github.com/istio/istio/issues/8572)  
  [istio/istio#8742](https://github.com/istio/istio/issues/8742)  
  [istio/istio#6135](https://github.com/istio/istio/issues/6135)
  [istio/proxy#1811](https://github.com/istio/proxy/issues/1811)
  [istio/proxy#1903](https://github.com/istio/proxy/issues/1903)
- Workgroup(s) I am involved with
  API Management,Networking,Policies & Telemetry

### Slack access
- If you'd like to join our developer Slack workspace, what is the email address you have associated with Slack?
zx3821ren@gmail.com

**Comment by m1093782566** [comment]
+1

**Comment by linsun** [comment]
per discussion in the TOC, we would like to see a bit more contribution to Istio before approving this membership request.  Also, pls have your sponsor document their sponsorship in the issue.

**Comment by linsun** [comment]
close the issue and pls reopen or open a new issue when you have met the requirement.  Would be really important to have sponsor document the sponsorship in a line or two when you open the new issue.

**Comment by x15zhang** [comment]
reopen
