### ISSUE TITLE
REQUEST: New membership for knightXun

### ISSUE THREAD

**Issue by knightXun** [istio/community#93]
### GitHub user id
- knightXun
### Company affiliation
- Huawei Technologies Co., Ltd. China
### Requirements
- [x] I have reviewed the [community membership guidelines](https://github.com/istio/community/blob/master/ROLES.md#member)
- [x] I have reviewed the [contribution guidelines](https://github.com/istio/community/blob/master/CONTRIBUTING.md)
- [x] I have enabled [2FA on my GitHub account](https://github.com/settings/security)
- [x] I have subscribed to the [istio-dev@](https://groups.google.com/forum/#!forum/istio-dev) mailing list
- [x] I have made multiple contributions to the project or community. Contributions may include, but are not limited to:
    - Authoring or reviewing PRs on GitHub
    - Filing or commenting on issues on GitHub
    - Contributing to working group or community discussions
- [x] I have two sponsors that meet the sponsorship requirements listed in the [community roles](./ROLES/#sponsor].
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to +1 on this issue to confirm they agree to sponsor this application.

### List of sponsors
- @hzxuzhonghu
- @sdake

### List of contributions to the Istio project
- PRs authored 
  istio/istio#5351  istio/istio#5431  istio/istio#8101 istio/istio#8177 istio/istio#8211 istio/istio#8235 istio/istio#8368 istio/istio#8371 istio/istio#8372 istio/istio#8608 istio/istio#8791 istio/istio#8794 istio/istio#9006 istio/istio#9028
- Workgroup(s) I am involved with
API Management,Networking,Policies
### Slack access
- badgangkiller@gmail.com

**Comment by sdake** [comment]
several housekeeping PRs.  Happy to sponsor.

/lgtm

**Comment by hzxuzhonghu** [comment]
+1

**Comment by gyliu513** [comment]
+1, thanks @knightXun for your contribution!!

**Comment by geeknoid** [comment]
Approved.
