### ISSUE TITLE
Slack Access

### ISSUE THREAD

**Issue by doonhammer** [istio/community#99]
I am a new member in the Istio Community and would like Slack access. My slack account is under jmcdowall@paloaltonetworks.com.

Is there anything else I need to do/provide?

Regards

John

**Comment by geeknoid** [comment]
You should have received an invitation to join. Let me know if it didn't go through.

**Comment by linsun** [comment]
@geeknoid should have invited you :)  welcome!

**Comment by geeknoid** [comment]
Done.
